"""
WhatsApp Bot service — Pure Report Delivery Channel.

WhatsApp is ONLY for:
1. Sending scheduled reports (daily, weekly, monthly, 6-month, yearly)
2. Sending alerts (restock, price drops, credit readiness, unusual activity)
3. Receiving report requests ("Ripoti ya leo" → send today's report)

WhatsApp is NOT for:
- Transaction recording (that's Msaidizi app, offline)
- Voice command processing for transactions (that's Msaidizi app)
- Interactive business advice (that's Msaidizi app → Biashara Intelligence cloud)

Workers use the Msaidizi app for recording transactions offline.
Deep analysis goes through Biashara Intelligence cloud model.
Reports are generated by the cloud and delivered via WhatsApp when workers are online.
"""

import re
from datetime import date, datetime
from typing import Optional, Tuple

import httpx
import structlog
from sqlalchemy import and_, select
from sqlalchemy.ext.asyncio import AsyncSession

from app.config import get_settings
from app.models.user import User
from app.services.report_gen import ReportGenerator
from app.utils.crypto import decrypt_value

logger = structlog.get_logger(__name__)
settings = get_settings()


class WhatsAppBot:
    """
    WhatsApp report delivery bot.

    Processes incoming messages ONLY for report requests.
    All transaction recording happens in the Msaidizi app (offline).
    All deep analysis happens in Biashara Intelligence cloud model.

    Supported inbound commands:
    - "Ripoti ya leo" / "Daily report" → send today's report
    - "Ripoti ya wiki" / "Weekly report" → send weekly report
    - "Ripoti ya mwezi" / "Monthly report" → send monthly report
    - "Ripoti" / "Report" → send latest available report
    - "Msaada" / "Help" → show available commands
    """

    # Command patterns — report requests ONLY
    COMMANDS = {
        "report": r"(ripoti|report|summary|muhtasari)",
        "help": r"(msaada|help|commands|amri)",
    }

    # Report sub-type patterns
    REPORT_SUBTYPES = {
        "daily": r"(leo|today|daily|ya leo|hii)",
        "weekly": r"(wiki|week|weekly|ya wiki)",
        "monthly": r"(mwezi|month|monthly|ya mwezi)",
        "semiannual": r"(nusu\s*mwaka|semi[\s-]?annual|6\s*month)",
        "annual": r"(mwaka|year|annual|ya mwaka)",
    }

    def __init__(self, db: AsyncSession):
        self.db = db
        self.report_gen = ReportGenerator(db)
        self.openwa_url = settings.OPENWA_URL

    async def process_message(
        self,
        phone: str,
        message: str,
        message_type: str = "text",
        media_url: Optional[str] = None,
    ) -> str:
        """
        Process an incoming WhatsApp message.

        Only handles report requests and help. All other messages
        are redirected to the Msaidizi app.

        Args:
            phone: Sender's phone number
            message: Message text
            message_type: Type of message (text, voice, image)
            media_url: URL if message contains media

        Returns:
            Response text to send back
        """
        logger.info(
            "whatsapp_message_received",
            phone=phone[:6] + "****",
            type=message_type,
            length=len(message),
        )

        # Find user
        user = await self._get_user_by_phone(phone)
        if not user:
            return self._welcome_message()

        # Normalize message
        msg = message.strip().lower()

        # Route to command handler
        command, args = self._parse_command(msg)

        if command == "report":
            return await self._handle_report_request(user, args)
        elif command == "help":
            return self._handle_help(user.language)

        # No command matched — redirect to Msaidizi app
        return self._redirect_to_app(user.language)

    def _parse_command(self, message: str) -> Tuple[Optional[str], str]:
        """
        Parse a message to extract command and arguments.

        Returns:
            Tuple of (command_name, remaining_args)
        """
        for command, pattern in self.COMMANDS.items():
            if re.search(pattern, message, re.IGNORECASE):
                remaining = re.sub(pattern, "", message, flags=re.IGNORECASE).strip()
                return command, remaining
        return None, message

    def _parse_report_subtype(self, args: str) -> str:
        """Determine which report type was requested."""
        for subtype, pattern in self.REPORT_SUBTYPES.items():
            if re.search(pattern, args, re.IGNORECASE):
                return subtype
        return "daily"  # Default to daily report

    async def _get_user_by_phone(self, phone: str) -> Optional[User]:
        """Look up user by phone number hash."""
        import hashlib
        phone_hash = hashlib.sha256(phone.encode()).hexdigest()
        result = await self.db.execute(
            select(User).where(
                and_(User.phone_hash == phone_hash, User.is_active == True)
            )
        )
        return result.scalar_one_or_none()

    # =========================================================================
    # Report Request Handler
    # =========================================================================

    async def _handle_report_request(self, user: User, args: str) -> str:
        """
        Handle report request — generate and return the appropriate report.

        Supported:
        - "Ripoti ya leo" → daily report
        - "Ripoti ya wiki" → weekly report
        - "Ripoti ya mwezi" → monthly report
        - "Ripoti ya nusu mwaka" → semi-annual report
        - "Ripoti ya mwaka" → annual report
        - "Ripoti" → daily report (default)
        """
        subtype = self._parse_report_subtype(args)
        lang = user.language or "sw"

        logger.info(
            "report_requested",
            user_id=str(user.id),
            subtype=subtype,
            language=lang,
        )

        try:
            if subtype == "daily":
                report = await self.report_gen.generate_daily_report(user)
                return self._format_daily_report(report, lang)

            elif subtype == "weekly":
                report = await self.report_gen.generate_weekly_report(user)
                return self._format_weekly_report(report, lang)

            elif subtype == "monthly":
                # Monthly report — generate from report generator
                return await self._generate_monthly_report(user, lang)

            elif subtype == "semiannual":
                return await self._generate_semiannual_report(user, lang)

            elif subtype == "annual":
                return await self._generate_annual_report(user, lang)

            else:
                report = await self.report_gen.generate_daily_report(user)
                return self._format_daily_report(report, lang)

        except Exception as e:
            logger.error(
                "report_generation_failed",
                user_id=str(user.id),
                subtype=subtype,
                error=str(e),
            )
            if lang == "sw":
                return (
                    "⚠️ *Samu, kuna tatizo la kutengeneza ripoti.*\n\n"
                    "Jaribu tena baadaye. Ripoti yako ya kila siku itatumwa "
                    "jioni kama kawaida."
                )
            else:
                return (
                    "⚠️ *Sorry, there was an issue generating your report.*\n\n"
                    "Please try again later. Your daily report will be sent "
                    "this evening as usual."
                )

    # =========================================================================
    # Help Handler
    # =========================================================================

    def _handle_help(self, language: str) -> str:
        """Show available commands — report requests only."""
        if language == "sw":
            return (
                "🇰🇪 *Msaidizi — Ripoti za Biashara*\n\n"
                "📋 *Omba Ripoti:*\n"
                "• \"Ripoti ya leo\" — Ripoti ya siku\n"
                "• \"Ripoti ya wiki\" — Ripoti ya wiki\n"
                "• \"Ripoti ya mwezi\" — Ripoti ya mwezi\n"
                "• \"Ripoti ya nusu mwaka\" — Ripoti ya nusu mwaka\n"
                "• \"Ripoti ya mwaka\" — Ripoti ya mwaka\n\n"
                "📲 *Ripoti za Kiotomatiki:*\n"
                "• Kila siku saa 1 jioni — muhtasari wa leo\n"
                "• Kila Jumatatu — ripoti ya wiki\n"
                "• Tarehe 1 ya kila mwezi — ripoti ya mwezi\n\n"
                "📱 *Rekodi Mauzo:*\n"
                "Tumia *Msaidizi App* kurekodi mauzo yako — "
                "inaweza kufanya kazi bila intaneti!\n\n"
                "🔗 Pakua app: https://msaidizi.app/download"
            )
        else:
            return (
                "🇰🇪 *Msaidizi — Business Reports*\n\n"
                "📋 *Request Reports:*\n"
                "• \"Daily report\" — Today's report\n"
                "• \"Weekly report\" — This week's report\n"
                "• \"Monthly report\" — This month's report\n"
                "• \"Semi-annual report\" — 6-month report\n"
                "• \"Annual report\" — Yearly report\n\n"
                "📲 *Automatic Reports:*\n"
                "• Every day at 7 PM — daily summary\n"
                "• Every Monday — weekly report\n"
                "• 1st of each month — monthly review\n\n"
                "📱 *Record Sales:*\n"
                "Use the *Msaidizi App* to record your transactions — "
                "it works offline!\n\n"
                "🔗 Download: https://msaidizi.app/download"
            )

    # =========================================================================
    # Welcome & Redirect Messages
    # =========================================================================

    def _welcome_message(self) -> str:
        """Welcome message for unknown users."""
        return (
            "🇰🇪 *Karibu Biashara Intelligence!*\n\n"
            "Mimi ninakutumia ripoti za biashara yako kupitia WhatsApp.\n\n"
            "📋 *Omba ripoti:*\n"
            "• \"Ripoti ya leo\" — Ripoti ya siku\n"
            "• \"Ripoti ya wiki\" — Ripoti ya wiki\n\n"
            "📱 *Rekodi mauzo yako kupitia Msaidizi App:*\n"
            "Inafanya kazi bila intaneti!\n\n"
            "🔗 Pakua app: https://msaidizi.app/download"
        )

    def _redirect_to_app(self, language: str) -> str:
        """
        Redirect non-report messages to the Msaidizi app.

        WhatsApp is NOT for recording transactions or interactive advice.
        That all happens in the Msaidizi app.
        """
        if language == "sw":
            return (
                "📱 *Tumia Msaidizi App*\n\n"
                "Kurekodi mauzo, kupata ushauri wa biashara, na "
                "kufuatilia stock yako — tumia *Msaidizi App*.\n\n"
                "WhatsApp hii ni kwa *ripoti tu*.\n\n"
                "📋 *Omba ripoti:*\n"
                "• \"Ripoti ya leo\"\n"
                "• \"Ripoti ya wiki\"\n\n"
                "🔗 Pakua app: https://msaidizi.app/download"
            )
        else:
            return (
                "📱 *Use the Msaidizi App*\n\n"
                "To record sales, get business advice, and track "
                "inventory — use the *Msaidizi App*.\n\n"
                "This WhatsApp channel is for *reports only*.\n\n"
                "📋 *Request reports:*\n"
                "• \"Daily report\"\n"
                "• \"Weekly report\"\n\n"
                "🔗 Download: https://msaidizi.app/download"
            )

    # =========================================================================
    # Report Formatting
    # =========================================================================

    def _format_daily_report(self, report, language: str) -> str:
        """Format daily report for WhatsApp display."""
        s = report.summary
        if language == "sw":
            text = (
                f"📊 *Ripoti ya Leo — {report.report_date.strftime('%d %B %Y')}*\n\n"
                f"💰 Mauzo: KES {s.total_sales:,.0f} ({s.transaction_count} mauzo)\n"
                f"📉 Gharama: KES {s.total_purchases + s.total_expenses:,.0f}\n"
                f"📈 Faida: KES {s.net_profit:,.0f} ({s.profit_margin_pct:.1f}%)\n"
            )
            if report.vs_yesterday_pct is not None:
                arrow = "↑" if report.vs_yesterday_pct > 0 else "↓"
                text += f"\n📊 Vs jana: {arrow} {abs(report.vs_yesterday_pct):.1f}%\n"
            if report.top_products:
                text += "\n🏆 *Bidhaa Bora:*\n"
                for p in report.top_products[:3]:
                    text += f"• {p.item}: KES {p.revenue:,.0f}\n"
            if report.low_stock_items:
                text += "\n⚠️ *Stock Ndogo:*\n"
                for item in report.low_stock_items:
                    text += f"• {item}\n"
            text += (
                "\n\n📱 *Rekodi mauzo kupitia Msaidizi App*\n"
                "🔗 https://msaidizi.app/download"
            )
        else:
            text = (
                f"📊 *Daily Report — {report.report_date.strftime('%d %B %Y')}*\n\n"
                f"💰 Sales: KES {s.total_sales:,.0f} ({s.transaction_count} txns)\n"
                f"📉 Costs: KES {s.total_purchases + s.total_expenses:,.0f}\n"
                f"📈 Profit: KES {s.net_profit:,.0f} ({s.profit_margin_pct:.1f}%)\n"
            )
            if report.vs_yesterday_pct is not None:
                arrow = "↑" if report.vs_yesterday_pct > 0 else "↓"
                text += f"\n📊 vs yesterday: {arrow} {abs(report.vs_yesterday_pct):.1f}%\n"
            if report.top_products:
                text += "\n🏆 *Top Products:*\n"
                for p in report.top_products[:3]:
                    text += f"• {p.item}: KES {p.revenue:,.0f}\n"
            text += (
                "\n\n📱 *Record sales via Msaidizi App*\n"
                "🔗 https://msaidizi.app/download"
            )

        return text

    def _format_weekly_report(self, report, language: str) -> str:
        """Format weekly report for WhatsApp display."""
        s = report.summary
        if language == "sw":
            text = (
                f"📊 *Ripoti ya Wiki*\n"
                f"{report.week_start} — {report.week_end}\n\n"
                f"💰 Mauzo: KES {s.total_sales:,.0f}\n"
                f"📈 Faida: KES {s.net_profit:,.0f}\n"
                f"📊 Transactions: {s.transaction_count}\n"
            )
            if report.wow_sales_change_pct is not None:
                arrow = "↑" if report.wow_sales_change_pct > 0 else "↓"
                text += f"\n📈 Wiki wiki: {arrow} {abs(report.wow_sales_change_pct):.1f}%\n"
            if report.best_day:
                text += f"\n🏆 Siku bora: {report.best_day}\n"
            if report.worst_day:
                text += f"📉 Siku dhaifu: {report.worst_day}\n"
        else:
            text = (
                f"📊 *Weekly Report*\n"
                f"{report.week_start} — {report.week_end}\n\n"
                f"💰 Sales: KES {s.total_sales:,.0f}\n"
                f"📈 Profit: KES {s.net_profit:,.0f}\n"
                f"📊 Transactions: {s.transaction_count}\n"
            )
            if report.wow_sales_change_pct is not None:
                arrow = "↑" if report.wow_sales_change_pct > 0 else "↓"
                text += f"\n📈 Week-over-week: {arrow} {abs(report.wow_sales_change_pct):.1f}%\n"
            if report.best_day:
                text += f"\n🏆 Best day: {report.best_day}\n"
            if report.worst_day:
                text += f"📉 Worst day: {report.worst_day}\n"

        return text

    async def _generate_monthly_report(self, user: User, language: str) -> str:
        """Generate monthly report text."""
        from app.services.pipeline import DataPipeline
        pipeline = DataPipeline(self.db)

        today = date.today()
        # First day of current month
        month_start = today.replace(day=1)

        metrics = await pipeline.aggregate_user_metrics(
            user.id, month_start, today
        )

        if language == "sw":
            return (
                f"📊 *Ripoti ya Mwezi — {today.strftime('%B %Y')}*\n\n"
                f"💰 Mauzo: KES {metrics['total_sales']:,.0f}\n"
                f"📉 Gharama: KES {metrics['total_purchases'] + metrics['total_expenses']:,.0f}\n"
                f"📈 Faida: KES {metrics['net_profit']:,.0f}\n"
                f"📊 Margin: {metrics['profit_margin_pct']:.1f}%\n"
                f"📋 Transactions: {metrics['transaction_count']}\n\n"
                f"💡 *Kwa ripoti kamili zaidi, tumia Msaidizi App*\n"
                f"🔗 https://msaidizi.app/download"
            )
        else:
            return (
                f"📊 *Monthly Report — {today.strftime('%B %Y')}*\n\n"
                f"💰 Sales: KES {metrics['total_sales']:,.0f}\n"
                f"📉 Costs: KES {metrics['total_purchases'] + metrics['total_expenses']:,.0f}\n"
                f"📈 Profit: KES {metrics['net_profit']:,.0f}\n"
                f"📊 Margin: {metrics['profit_margin_pct']:.1f}%\n"
                f"📋 Transactions: {metrics['transaction_count']}\n\n"
                f"💡 *For full analysis, use Msaidizi App*\n"
                f"🔗 https://msaidizi.app/download"
            )

    async def _generate_semiannual_report(self, user: User, language: str) -> str:
        """Generate semi-annual report text."""
        from app.services.pipeline import DataPipeline
        pipeline = DataPipeline(self.db)

        today = date.today()
        if today.month <= 6:
            period_start = date(today.year, 1, 1)
            period_label = f"Jan — Jun {today.year}"
        else:
            period_start = date(today.year, 7, 1)
            period_label = f"Jul — Dec {today.year}"

        metrics = await pipeline.aggregate_user_metrics(
            user.id, period_start, today
        )

        if language == "sw":
            return (
                f"📊 *Ripoti ya Nusu Mwaka*\n"
                f"{period_label}\n\n"
                f"💰 Mauzo: KES {metrics['total_sales']:,.0f}\n"
                f"📈 Faida: KES {metrics['net_profit']:,.0f}\n"
                f"📊 Margin: {metrics['profit_margin_pct']:.1f}%\n"
                f"📋 Transactions: {metrics['transaction_count']}\n\n"
                f"💡 *Kwa uchambuzi wa kina, tumia Biashara Intelligence*\n"
                f"📱 https://msaidizi.app/download"
            )
        else:
            return (
                f"📊 *Semi-Annual Report*\n"
                f"{period_label}\n\n"
                f"💰 Sales: KES {metrics['total_sales']:,.0f}\n"
                f"📈 Profit: KES {metrics['net_profit']:,.0f}\n"
                f"📊 Margin: {metrics['profit_margin_pct']:.1f}%\n"
                f"📋 Transactions: {metrics['transaction_count']}\n\n"
                f"💡 *For deep analysis, use Biashara Intelligence*\n"
                f"📱 https://msaidizi.app/download"
            )

    async def _generate_annual_report(self, user: User, language: str) -> str:
        """Generate annual report text."""
        from app.services.pipeline import DataPipeline
        pipeline = DataPipeline(self.db)

        today = date.today()
        year_start = date(today.year, 1, 1)

        metrics = await pipeline.aggregate_user_metrics(
            user.id, year_start, today
        )

        if language == "sw":
            return (
                f"📊 *Ripoti ya Mwaka — {today.year}*\n\n"
                f"💰 Mauzo: KES {metrics['total_sales']:,.0f}\n"
                f"📈 Faida: KES {metrics['net_profit']:,.0f}\n"
                f"📊 Margin: {metrics['profit_margin_pct']:.1f}%\n"
                f"📋 Transactions: {metrics['transaction_count']}\n\n"
                f"💡 *Kwa ripoti kamili ya mwaka, tumia Biashara Intelligence*\n"
                f"📱 https://msaidizi.app/download"
            )
        else:
            return (
                f"📊 *Annual Report — {today.year}*\n\n"
                f"💰 Sales: KES {metrics['total_sales']:,.0f}\n"
                f"📈 Profit: KES {metrics['net_profit']:,.0f}\n"
                f"📊 Margin: {metrics['profit_margin_pct']:.1f}%\n"
                f"📋 Transactions: {metrics['transaction_count']}\n\n"
                f"💡 *For full annual analysis, use Biashara Intelligence*\n"
                f"📱 https://msaidizi.app/download"
            )

    # =========================================================================
    # Outbound Messaging
    # =========================================================================

    async def send_message(
        self,
        phone: str,
        message: str,
    ) -> bool:
        """
        Send a WhatsApp message via OpenWA.

        Args:
            phone: Recipient phone number (with country code)
            message: Message text

        Returns:
            True if sent successfully
        """
        try:
            async with httpx.AsyncClient() as client:
                response = await client.post(
                    f"{self.openwa_url}/send-message",
                    json={
                        "to": phone,
                        "message": message,
                    },
                    headers={
                        "Authorization": f"Bearer {settings.OPENWA_WEBHOOK_SECRET}",
                    },
                    timeout=10.0,
                )
                if response.status_code == 200:
                    logger.info("whatsapp_message_sent", phone=phone[:6] + "****")
                    return True
                else:
                    logger.error(
                        "whatsapp_send_failed",
                        status=response.status_code,
                        body=response.text,
                    )
                    return False
        except Exception as e:
            logger.error("whatsapp_send_error", error=str(e))
            return False

    async def send_image(
        self,
        phone: str,
        image_data: bytes,
        caption: str,
    ) -> bool:
        """
        Send a WhatsApp image message via OpenWA.

        Args:
            phone: Recipient phone number
            image_data: Image bytes (PNG/JPEG)
            caption: Image caption text

        Returns:
            True if sent successfully
        """
        try:
            import base64
            image_b64 = base64.b64encode(image_data).decode("utf-8")

            async with httpx.AsyncClient() as client:
                response = await client.post(
                    f"{self.openwa_url}/send-image",
                    json={
                        "to": phone,
                        "image": image_b64,
                        "caption": caption,
                    },
                    headers={
                        "Authorization": f"Bearer {settings.OPENWA_WEBHOOK_SECRET}",
                    },
                    timeout=15.0,
                )
                if response.status_code == 200:
                    logger.info("whatsapp_image_sent", phone=phone[:6] + "****")
                    return True
                else:
                    logger.error(
                        "whatsapp_image_send_failed",
                        status=response.status_code,
                        body=response.text,
                    )
                    return False
        except Exception as e:
            logger.error("whatsapp_image_send_error", error=str(e))
            return False
