"""
WhatsApp Delivery Service — Biashara Intelligence Report Channel.

WhatsApp is a PURE REPORT DELIVERY CHANNEL. Workers receive reports when online.

Reports are generated by Biashara Intelligence cloud model and delivered
via WhatsApp. The Msaidizi app handles transaction recording (offline).

NOT for:
- Transaction recording (Msaidizi app, offline)
- Deep analysis requests (Msaidizi app → Biashara Intelligence cloud API)
- Interactive commands (Msaidizi app)

ONLY for:
- Scheduled reports (daily, weekly, monthly, 6-month, yearly)
- Alerts (restock, price drop, credit readiness, unusual activity)
- Report requests ("Ripoti ya leo")

Report Schedule:
- Daily: 7 PM EAT (evening briefing)
- Weekly: Monday 8 AM EAT (weekly summary)
- Monthly: 1st of month 9 AM EAT (monthly review)
- Semi-annual: June 30 & December 31 (semi-annual review)
- Annual: December 31 (annual review)
"""

import io
from datetime import date, datetime, timedelta, timezone
from typing import Dict, List, Optional

import structlog
from sqlalchemy import and_, select
from sqlalchemy.ext.asyncio import AsyncSession

from app.config import get_settings
from app.models.user import User
from app.services.report_gen import ReportGenerator
from app.services.whatsapp_bot import WhatsAppBot
from app.utils.crypto import decrypt_value

logger = structlog.get_logger(__name__)
settings = get_settings()

# EAT timezone offset (UTC+3)
EAT_OFFSET = timedelta(hours=3)


def eat_now() -> datetime:
    """Get current time in East Africa Time."""
    return datetime.now(timezone.utc) + EAT_OFFSET


class WhatsAppDelivery:
    """
    WhatsApp delivery channel for Biashara Intelligence reports.

    Workers receive reports when online. Reports are generated by
    Biashara Intelligence cloud model and delivered via WhatsApp.

    This service orchestrates:
    1. Report generation (via ReportGenerator)
    2. Chart generation (via WhatsAppCharts)
    3. Message formatting (language-aware)
    4. Delivery via OpenWA

    Usage:
        delivery = WhatsAppDelivery(db)
        await delivery.send_daily_report(worker_id)
        await delivery.send_alert(worker_id, "restock")
    """

    def __init__(self, db: AsyncSession):
        self.db = db
        self.bot = WhatsAppBot(db)
        self.report_gen = ReportGenerator(db)

    # =========================================================================
    # Scheduled Reports
    # =========================================================================

    async def send_daily_report(self, worker_id: str) -> bool:
        """
        Send daily report via WhatsApp.

        Called at 7 PM EAT by the report scheduler.
        Includes: sales, costs, profit, top products, stock alerts.

        Args:
            worker_id: Worker UUID

        Returns:
            True if sent successfully
        """
        user = await self._get_user(worker_id)
        if not user:
            logger.error("daily_report_user_not_found", worker_id=worker_id)
            return False

        phone = decrypt_value(user.phone_encrypted)
        lang = user.language or "sw"

        try:
            report = await self.report_gen.generate_daily_report(user)
            message = self.bot._format_daily_report(report, lang)

            success = await self.bot.send_message(phone, message)
            if success:
                logger.info(
                    "daily_report_delivered",
                    worker_id=worker_id,
                    language=lang,
                )
            return success

        except Exception as e:
            logger.error(
                "daily_report_delivery_failed",
                worker_id=worker_id,
                error=str(e),
            )
            return False

    async def send_weekly_report(self, worker_id: str) -> bool:
        """
        Send weekly report via WhatsApp.

        Called Monday 8 AM EAT by the report scheduler.
        Includes: weekly summary, trends, best/worst days, chart image.

        Args:
            worker_id: Worker UUID

        Returns:
            True if sent successfully
        """
        user = await self._get_user(worker_id)
        if not user:
            logger.error("weekly_report_user_not_found", worker_id=worker_id)
            return False

        phone = decrypt_value(user.phone_encrypted)
        lang = user.language or "sw"

        try:
            report = await self.report_gen.generate_weekly_report(user)
            message = self.bot._format_weekly_report(report, lang)

            # Try to generate and send chart image
            chart_data = await self._generate_weekly_chart(report, lang)
            if chart_data:
                success = await self.bot.send_image(phone, chart_data, message)
            else:
                success = await self.bot.send_message(phone, message)

            if success:
                logger.info(
                    "weekly_report_delivered",
                    worker_id=worker_id,
                    language=lang,
                    with_chart=chart_data is not None,
                )
            return success

        except Exception as e:
            logger.error(
                "weekly_report_delivery_failed",
                worker_id=worker_id,
                error=str(e),
            )
            return False

    async def send_monthly_report(self, worker_id: str) -> bool:
        """
        Send monthly report via WhatsApp.

        Called 1st of month 9 AM EAT by the report scheduler.
        Includes: monthly summary, trends, expense breakdown, peer comparison.

        Args:
            worker_id: Worker UUID

        Returns:
            True if sent successfully
        """
        user = await self._get_user(worker_id)
        if not user:
            return False

        phone = decrypt_value(user.phone_encrypted)
        lang = user.language or "sw"

        try:
            message = await self.bot._generate_monthly_report(user, lang)
            success = await self.bot.send_message(phone, message)

            if success:
                logger.info("monthly_report_delivered", worker_id=worker_id)
            return success

        except Exception as e:
            logger.error(
                "monthly_report_delivery_failed",
                worker_id=worker_id,
                error=str(e),
            )
            return False

    async def send_semiannual_report(self, worker_id: str) -> bool:
        """
        Send semi-annual report via WhatsApp.

        Called June 30 and December 31 by the report scheduler.
        Includes: 6-month summary, growth trends, market position.

        Args:
            worker_id: Worker UUID

        Returns:
            True if sent successfully
        """
        user = await self._get_user(worker_id)
        if not user:
            return False

        phone = decrypt_value(user.phone_encrypted)
        lang = user.language or "sw"

        try:
            message = await self.bot._generate_semiannual_report(user, lang)
            success = await self.bot.send_message(phone, message)

            if success:
                logger.info("semiannual_report_delivered", worker_id=worker_id)
            return success

        except Exception as e:
            logger.error(
                "semiannual_report_delivery_failed",
                worker_id=worker_id,
                error=str(e),
            )
            return False

    async def send_annual_report(self, worker_id: str) -> bool:
        """
        Send annual report via WhatsApp.

        Called December 31 by the report scheduler.
        Includes: full year summary, YoY comparison, growth analysis.

        Args:
            worker_id: Worker UUID

        Returns:
            True if sent successfully
        """
        user = await self._get_user(worker_id)
        if not user:
            return False

        phone = decrypt_value(user.phone_encrypted)
        lang = user.language or "sw"

        try:
            message = await self.bot._generate_annual_report(user, lang)
            success = await self.bot.send_message(phone, message)

            if success:
                logger.info("annual_report_delivered", worker_id=worker_id)
            return success

        except Exception as e:
            logger.error(
                "annual_report_delivery_failed",
                worker_id=worker_id,
                error=str(e),
            )
            return False

    # =========================================================================
    # Alerts
    # =========================================================================

    async def send_alert(
        self,
        worker_id: str,
        alert_type: str,
        alert_data: Optional[Dict] = None,
    ) -> bool:
        """
        Send an alert via WhatsApp.

        Alert types:
        - restock: Item below restock threshold
        - price_drop: Market price dropped for worker's products
        - credit_readiness: Worker qualifies for credit
        - unusual_activity: Unusual transaction pattern detected

        Args:
            worker_id: Worker UUID
            alert_type: Type of alert
            alert_data: Additional alert context

        Returns:
            True if sent successfully
        """
        user = await self._get_user(worker_id)
        if not user:
            return False

        phone = decrypt_value(user.phone_encrypted)
        lang = user.language or "sw"
        data = alert_data or {}

        try:
            message = self._format_alert(alert_type, data, lang)
            success = await self.bot.send_message(phone, message)

            if success:
                logger.info(
                    "alert_delivered",
                    worker_id=worker_id,
                    alert_type=alert_type,
                )
            return success

        except Exception as e:
            logger.error(
                "alert_delivery_failed",
                worker_id=worker_id,
                alert_type=alert_type,
                error=str(e),
            )
            return False

    def _format_alert(
        self, alert_type: str, data: Dict, language: str
    ) -> str:
        """Format an alert message for WhatsApp delivery."""

        if alert_type == "restock":
            item = data.get("item", "?")
            current = data.get("current_stock", 0)
            threshold = data.get("restock_threshold", 0)

            if language == "sw":
                return (
                    f"⚠️ *Taarifa ya Stock*\n\n"
                    f"📦 *{item}* imepungua!\n"
                    f"Stock ya sasa: {current}\n"
                    f"Kiwango cha chini: {threshold}\n\n"
                    f"🔔 *Nunua zaidi sasa ili usipitwe na wateja.*\n\n"
                    f"📱 Tumia Msaidizi App kurekodi ununuzi.\n"
                    f"🔗 https://msaidizi.app/download"
                )
            else:
                return (
                    f"⚠️ *Stock Alert*\n\n"
                    f"📦 *{item}* is running low!\n"
                    f"Current stock: {current}\n"
                    f"Minimum threshold: {threshold}\n\n"
                    f"🔔 *Restock now to avoid stockouts.*\n\n"
                    f"📱 Use Msaidizi App to record purchases.\n"
                    f"🔗 https://msaidizi.app/download"
                )

        elif alert_type == "price_drop":
            item = data.get("item", "?")
            old_price = data.get("old_price", 0)
            new_price = data.get("new_price", 0)
            drop_pct = data.get("drop_pct", 0)

            if language == "sw":
                return (
                    f"📉 *Bei Zimepungua*\n\n"
                    f"🏪 *{item}*:\n"
                    f"• Bei ya awali: KES {old_price:,.0f}\n"
                    f"• Bei ya sasa: KES {new_price:,.0f}\n"
                    f"• Kupungua: {drop_pct:.0f}%\n\n"
                    f"💡 *Fursa nzuri ya kununua stock!*\n\n"
                    f"📱 Tumia Msaidizi App.\n"
                    f"🔗 https://msaidizi.app/download"
                )
            else:
                return (
                    f"📉 *Price Drop Alert*\n\n"
                    f"🏪 *{item}*:\n"
                    f"• Previous price: KES {old_price:,.0f}\n"
                    f"• Current price: KES {new_price:,.0f}\n"
                    f"• Drop: {drop_pct:.0f}%\n\n"
                    f"💡 *Good opportunity to buy stock!*\n\n"
                    f"📱 Use Msaidizi App.\n"
                    f"🔗 https://msaidizi.app/download"
                )

        elif alert_type == "credit_readiness":
            score = data.get("alama_score", 0)
            band = data.get("band", "unknown")

            if language == "sw":
                return (
                    f"🏦 *Fursa ya Mkopo*\n\n"
                    f"Alama yako ya biashara: *{score}/100* ({band})\n\n"
                    f"💡 *Una sifa za kuomba mkopo!*\n"
                    f"Mkopo unaweza kukusaidia kuongeza stock "
                    f"na kupanua biashara yako.\n\n"
                    f"📱 Tumia Msaidizi App kuomba.\n"
                    f"🔗 https://msaidizi.app/download"
                )
            else:
                return (
                    f"🏦 *Credit Opportunity*\n\n"
                    f"Your business score: *{score}/100* ({band})\n\n"
                    f"💡 *You qualify for credit!*\n"
                    f"A loan can help you increase stock "
                    f"and grow your business.\n\n"
                    f"📱 Apply via Msaidizi App.\n"
                    f"🔗 https://msaidizi.app/download"
                )

        elif alert_type == "unusual_activity":
            item = data.get("item", "?")
            today_count = data.get("today_count", 0)
            avg_count = data.get("avg_count", 0)

            if language == "sw":
                return (
                    f"📊 *Mauzo ya Ajabu*\n\n"
                    f"🏪 *{item}* — mauzo yameongezeka sana leo!\n"
                    f"• Mauzo ya leo: {today_count}\n"
                    f"• Wastani wa kila siku: {avg_count:.0f}\n\n"
                    f"💡 *Angalia bei — mahitaji yamepanda!*\n\n"
                    f"📱 Tumia Msaidizi App.\n"
                    f"🔗 https://msaidizi.app/download"
                )
            else:
                return (
                    f"📊 *Unusual Activity*\n\n"
                    f"🏪 *{item}* — sales spike today!\n"
                    f"• Today's sales: {today_count}\n"
                    f"• Daily average: {avg_count:.0f}\n\n"
                    f"💡 *Check prices — demand has increased!*\n\n"
                    f"📱 Use Msaidizi App.\n"
                    f"🔗 https://msaidizi.app/download"
                )

        # Default alert
        if language == "sw":
            return f"🔔 *Taarifa*\n\n{data.get('message', 'Angalia biashara yako.')}"
        else:
            return f"🔔 *Alert*\n\n{data.get('message', 'Check your business.')}"

    # =========================================================================
    # Report Request Handling
    # =========================================================================

    async def handle_report_request(
        self, worker_id: str, request: str
    ) -> bool:
        """
        Handle a report request from a worker.

        Workers can request reports via WhatsApp by sending messages like:
        - "Ripoti ya leo" → daily report
        - "Ripoti ya wiki" → weekly report
        - "Ripoti ya mwezi" → monthly report

        Args:
            worker_id: Worker UUID
            request: The request message text

        Returns:
            True if report was sent successfully
        """
        user = await self._get_user(worker_id)
        if not user:
            return False

        phone = decrypt_value(user.phone_encrypted)

        try:
            response = await self.bot.process_message(
                phone=phone,
                message=request,
                message_type="text",
            )
            success = await self.bot.send_message(phone, response)

            if success:
                logger.info(
                    "report_request_handled",
                    worker_id=worker_id,
                    request=request[:50],
                )
            return success

        except Exception as e:
            logger.error(
                "report_request_failed",
                worker_id=worker_id,
                error=str(e),
            )
            return False

    # =========================================================================
    # Bulk Delivery (for scheduler)
    # =========================================================================

    async def send_daily_reports_to_all(self) -> Dict[str, int]:
        """
        Send daily reports to all active WhatsApp users.

        Called by the report scheduler at 7 PM EAT.

        Returns:
            Dict with total, sent, failed counts
        """
        return await self._bulk_send("daily")

    async def send_weekly_reports_to_all(self) -> Dict[str, int]:
        """
        Send weekly reports to all active WhatsApp users.

        Called by the report scheduler on Monday 8 AM EAT.

        Returns:
            Dict with total, sent, failed counts
        """
        return await self._bulk_send("weekly")

    async def send_monthly_reports_to_all(self) -> Dict[str, int]:
        """
        Send monthly reports to all active WhatsApp users.

        Called by the report scheduler on 1st of month 9 AM EAT.

        Returns:
            Dict with total, sent, failed counts
        """
        return await self._bulk_send("monthly")

    async def _bulk_send(self, report_type: str) -> Dict[str, int]:
        """Send a specific report type to all active WhatsApp users."""
        result = await self.db.execute(
            select(User).where(
                and_(
                    User.is_active == True,
                    User.channel == "whatsapp",
                )
            )
        )
        users = result.scalars().all()

        sent = 0
        failed = 0

        send_methods = {
            "daily": self.send_daily_report,
            "weekly": self.send_weekly_report,
            "monthly": self.send_monthly_report,
            "semiannual": self.send_semiannual_report,
            "annual": self.send_annual_report,
        }

        send_fn = send_methods.get(report_type, self.send_daily_report)

        for user in users:
            try:
                success = await send_fn(str(user.id))
                if success:
                    sent += 1
                else:
                    failed += 1
            except Exception as e:
                logger.error(
                    "bulk_send_user_failed",
                    user_id=str(user.id),
                    report_type=report_type,
                    error=str(e),
                )
                failed += 1

        logger.info(
            "bulk_send_completed",
            report_type=report_type,
            total=len(users),
            sent=sent,
            failed=failed,
        )

        return {
            "total": len(users),
            "sent": sent,
            "failed": failed,
        }

    # =========================================================================
    # Chart Generation
    # =========================================================================

    async def _generate_weekly_chart(
        self, report, language: str
    ) -> Optional[bytes]:
        """
        Generate a chart image for the weekly report.

        Returns PNG image bytes, or None if chart generation fails.
        """
        try:
            from app.services.whatsapp_charts import WhatsAppCharts
            charts = WhatsAppCharts()
            return charts.generate_weekly_sales_chart(report, language)
        except ImportError:
            logger.warning("whatsapp_charts_not_available")
            return None
        except Exception as e:
            logger.warning("chart_generation_failed", error=str(e))
            return None

    # =========================================================================
    # Helpers
    # =========================================================================

    async def _get_user(self, worker_id: str) -> Optional[User]:
        """Get user by ID."""
        result = await self.db.execute(
            select(User).where(
                and_(User.id == worker_id, User.is_active == True)
            )
        )
        return result.scalar_one_or_none()
