//! Trace Analysis Pipeline — Loop 4: Automated Harness Improvement
//!
//! Reads aggregated traces from mobile devices, identifies patterns
//! in agent behavior, and generates improvement recommendations for:
//!   - IntentRouter weight adjustments
//!   - ToolGraph edge modifications
//!   - Context assembly priority changes
//!
//! This is the "brain" of the hill-climbing flywheel:
//!   Traces → Analysis → Recommendations → Harness Updates → Better Traces → ...
//!
//! Privacy: Only processes anonymized, aggregated data. k-anonymity (≥50 users).

use chrono::{DateTime, Duration, Utc};
use serde::{Deserialize, Serialize};
use sqlx::PgPool;
use std::collections::HashMap;
use tracing::{info, warn};
use uuid::Uuid;

// ─── Trace Data Structures ──────────────────────────────────────────────

/// An anonymized agent trace received from a mobile device.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ReceivedTrace {
    pub trace_id: String,
    pub timestamp: i64,
    pub input_hash: String,
    pub intent_type: String,
    pub intent_confidence: f64,
    pub intent_tier: String,
    pub tools_selected: serde_json::Value,   // JSON array of tool names
    pub tools_succeeded: i32,
    pub tools_failed: i32,
    pub tool_results_json: serde_json::Value,
    pub prompt_tokens: i32,
    pub output_tokens: i32,
    pub total_latency_ms: i64,
    pub intent_routing_ms: i64,
    pub tool_execution_ms: i64,
    pub llm_inference_ms: i64,
    pub final_confidence: f64,
    pub ooda_iterations: i32,
    pub guardrail_blocked: bool,
    pub user_feedback: Option<i32>,           // null=unrated, 1=positive, 0=negative
    pub user_correction: Option<String>,
    pub correction_latency_ms: Option<i64>,
    pub ooda_phase: String,
    pub is_voice: bool,
    pub business_category: Option<String>,
    pub region: Option<String>,
}

// ─── Analysis Results ───────────────────────────────────────────────────

/// Aggregate statistics for a single intent type.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IntentStats {
    pub intent_type: String,
    pub total_runs: i64,
    pub success_count: i64,
    pub failure_count: i64,
    pub success_rate: f64,
    pub avg_confidence: f64,
    pub avg_latency_ms: f64,
    pub correction_count: i64,
    pub correction_rate: f64,
    pub positive_feedback: i64,
    pub negative_feedback: i64,
    pub feedback_rate: f64,
    /// Which tier resolves this intent most often
    pub primary_tier: String,
    /// Tier distribution: tier → count
    pub tier_distribution: HashMap<String, i64>,
}

/// Tool usage pattern: how a tool performs across intents.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolPattern {
    pub tool_name: String,
    pub total_uses: i64,
    pub success_count: i64,
    pub failure_count: i64,
    pub success_rate: f64,
    /// Which intents use this tool
    pub used_by_intents: Vec<String>,
    /// Average latency when this tool is involved
    pub avg_latency_ms: f64,
}

/// A single improvement recommendation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Recommendation {
    pub id: String,
    pub recommendation_type: RecommendationType,
    pub priority: RecommendationPriority,
    pub description: String,
    pub target: String,                       // e.g., "intent:RECORD_SALE", "tool:check_stock"
    pub current_value: serde_json::Value,
    pub recommended_value: serde_json::Value,
    pub confidence: f64,                      // 0.0–1.0, how confident we are
    pub expected_improvement: String,         // e.g., "success_rate +5%"
    pub evidence: Vec<String>,                // supporting data points
    pub created_at: DateTime<Utc>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum RecommendationType {
    /// Adjust IntentRouter weight for an intent
    IntentWeightAdjustment,
    /// Add or remove a ToolGraph edge
    ToolGraphEdgeChange,
    /// Adjust context assembly priority
    ContextPriorityChange,
    /// Add new pattern keyword for an intent
    PatternKeywordAddition,
    /// Change tier escalation threshold
    TierThresholdChange,
    /// Remove a tool from an intent's tool set
    ToolRemoval,
    /// Add a tool to an intent's tool set
    ToolAddition,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialOrd, Ord, PartialEq, Eq)]
pub enum RecommendationPriority {
    Critical,   // success_rate < 50%
    High,       // success_rate < 70%
    Medium,     // correction_rate > 20%
    Low,        // minor optimization
}

/// Full analysis report generated by the trace analysis pipeline.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AnalysisReport {
    pub report_id: String,
    pub analysis_window_start: DateTime<Utc>,
    pub analysis_window_end: DateTime<Utc>,
    pub total_traces_analyzed: i64,
    pub intent_stats: Vec<IntentStats>,
    pub tool_patterns: Vec<ToolPattern>,
    pub recommendations: Vec<Recommendation>,
    pub generated_at: DateTime<Utc>,
}

// ─── Trace Analyzer ─────────────────────────────────────────────────────

/// The core trace analysis engine.
///
/// Reads traces from the `agent_traces` table, computes aggregate statistics,
/// identifies problematic patterns, and generates actionable recommendations.
pub struct TraceAnalyzer {
    db: PgPool,
    /// Minimum number of traces for a pattern to be statistically significant
    min_sample_size: i64,
    /// Success rate below this triggers a critical recommendation
    critical_success_threshold: f64,
    /// Correction rate above this triggers a recommendation
    correction_threshold: f64,
}

impl TraceAnalyzer {
    pub fn new(db: PgPool) -> Self {
        Self {
            db,
            min_sample_size: 50,
            critical_success_threshold: 0.50,
            correction_threshold: 0.20,
        }
    }

    /// Run a full analysis on traces within the given time window.
    /// Returns an AnalysisReport with statistics and recommendations.
    pub async fn analyze(
        &self,
        window_start: DateTime<Utc>,
        window_end: DateTime<Utc>,
    ) -> anyhow::Result<AnalysisReport> {
        info!(
            "TraceAnalyzer: analyzing traces from {} to {}",
            window_start, window_end
        );

        // 1. Load traces from database
        let traces = self.load_traces(window_start, window_end).await?;
        let total_traces = traces.len() as i64;

        if total_traces < self.min_sample_size {
            warn!(
                "TraceAnalyzer: only {} traces (need {}), skipping analysis",
                total_traces, self.min_sample_size
            );
            return Ok(AnalysisReport {
                report_id: Uuid::new_v4().to_string(),
                analysis_window_start: window_start,
                analysis_window_end: window_end,
                total_traces_analyzed: total_traces,
                intent_stats: vec![],
                tool_patterns: vec![],
                recommendations: vec![],
                generated_at: Utc::now(),
            });
        }

        info!("TraceAnalyzer: loaded {} traces", total_traces);

        // 2. Compute per-intent statistics
        let intent_stats = self.compute_intent_stats(&traces);
        info!("TraceAnalyzer: computed stats for {} intents", intent_stats.len());

        // 3. Compute tool usage patterns
        let tool_patterns = self.compute_tool_patterns(&traces);
        info!("TraceAnalyzer: computed patterns for {} tools", tool_patterns.len());

        // 4. Generate recommendations
        let recommendations = self.generate_recommendations(&intent_stats, &tool_patterns);
        info!(
            "TraceAnalyzer: generated {} recommendations",
            recommendations.len()
        );

        Ok(AnalysisReport {
            report_id: Uuid::new_v4().to_string(),
            analysis_window_start: window_start,
            analysis_window_end: window_end,
            total_traces_analyzed: total_traces,
            intent_stats,
            tool_patterns,
            recommendations,
            generated_at: Utc::now(),
        })
    }

    // ── Data Loading ───────────────────────────────────────────────────

    async fn load_traces(
        &self,
        start: DateTime<Utc>,
        end: DateTime<Utc>,
    ) -> anyhow::Result<Vec<ReceivedTrace>> {
        let rows: Vec<(String, i64, String, String, f64, String, serde_json::Value, i32, i32, serde_json::Value, i32, i32, i64, i64, i64, i64, f64, i32, bool, Option<i32>, Option<String>, Option<i64>, String, bool, Option<String>, Option<String>)> =
            sqlx::query_as(
                r#"
                SELECT trace_id, timestamp, raw_input_hash, intent_type, intent_confidence,
                       intent_tier, tools_selected::jsonb, tools_succeeded, tools_failed,
                       tool_results_json::jsonb, prompt_token_count, output_token_count,
                       total_latency_ms, intent_routing_ms, tool_execution_ms, llm_inference_ms,
                       final_confidence, ooda_iterations, guardrail_blocked,
                       user_feedback, user_correction, correction_latency_ms,
                       ooda_phase, is_voice, business_category, region
                FROM agent_traces
                WHERE created_at BETWEEN $1 AND $2
                ORDER BY timestamp ASC
                "#,
            )
            .bind(start)
            .bind(end)
            .fetch_all(&self.db)
            .await?;

        let traces = rows
            .into_iter()
            .map(|r| ReceivedTrace {
                trace_id: r.0,
                timestamp: r.1,
                input_hash: r.2,
                intent_type: r.3,
                intent_confidence: r.4,
                intent_tier: r.5,
                tools_selected: r.6,
                tools_succeeded: r.7,
                tools_failed: r.8,
                tool_results_json: r.9,
                prompt_tokens: r.10,
                output_tokens: r.11,
                total_latency_ms: r.12,
                intent_routing_ms: r.13,
                tool_execution_ms: r.14,
                llm_inference_ms: r.15,
                final_confidence: r.16,
                ooda_iterations: r.17,
                guardrail_blocked: r.18,
                user_feedback: r.19,
                user_correction: r.20,
                correction_latency_ms: r.21,
                ooda_phase: r.22,
                is_voice: r.23,
                business_category: r.24,
                region: r.25,
            })
            .collect();

        Ok(traces)
    }

    // ── Intent Statistics ──────────────────────────────────────────────

    fn compute_intent_stats(&self, traces: &[ReceivedTrace]) -> Vec<IntentStats> {
        let mut intent_map: HashMap<String, Vec<&ReceivedTrace>> = HashMap::new();
        for trace in traces {
            intent_map
                .entry(trace.intent_type.clone())
                .or_default()
                .push(trace);
        }

        intent_map
            .into_iter()
            .filter(|(_, group)| group.len() as i64 >= self.min_sample_size / 5) // lower threshold per-intent
            .map(|(intent_type, group)| {
                let total = group.len() as i64;
                let success_count = group.iter().filter(|t| t.tools_failed == 0).count() as i64;
                let failure_count = total - success_count;
                let success_rate = success_count as f64 / total as f64;

                let avg_confidence =
                    group.iter().map(|t| t.final_confidence).sum::<f64>() / total as f64;

                let avg_latency =
                    group.iter().map(|t| t.total_latency_ms).sum::<i64>() as f64 / total as f64;

                let correction_count = group.iter().filter(|t| t.user_correction.is_some()).count() as i64;
                let correction_rate = correction_count as f64 / total as f64;

                let positive = group.iter().filter(|t| t.user_feedback == Some(1)).count() as i64;
                let negative = group.iter().filter(|t| t.user_feedback == Some(0)).count() as i64;
                let feedback_total = positive + negative;
                let feedback_rate = if feedback_total > 0 {
                    positive as f64 / feedback_total as f64
                } else {
                    0.0
                };

                // Tier distribution
                let mut tier_dist: HashMap<String, i64> = HashMap::new();
                for t in &group {
                    *tier_dist.entry(t.intent_tier.clone()).or_insert(0) += 1;
                }
                let primary_tier = tier_dist
                    .iter()
                    .max_by_key(|(_, v)| *v)
                    .map(|(k, _)| k.clone())
                    .unwrap_or_else(|| "UNKNOWN".to_string());

                IntentStats {
                    intent_type,
                    total_runs: total,
                    success_count,
                    failure_count,
                    success_rate,
                    avg_confidence,
                    avg_latency_ms: avg_latency,
                    correction_count,
                    correction_rate,
                    positive_feedback: positive,
                    negative_feedback: negative,
                    feedback_rate,
                    primary_tier,
                    tier_distribution: tier_dist,
                }
            })
            .collect()
    }

    // ── Tool Patterns ──────────────────────────────────────────────────

    fn compute_tool_patterns(&self, traces: &[ReceivedTrace]) -> Vec<ToolPattern> {
        let mut tool_map: HashMap<String, Vec<&ReceivedTrace>> = HashMap::new();

        for trace in traces {
            if let Ok(tools) = serde_json::from_value::<Vec<String>>(trace.tools_selected.clone()) {
                for tool in tools {
                    tool_map.entry(tool).or_default().push(trace);
                }
            }
        }

        tool_map
            .into_iter()
            .map(|(tool_name, group)| {
                let total = group.len() as i64;
                let success_count = group.iter().filter(|t| t.tools_failed == 0).count() as i64;
                let failure_count = total - success_count;
                let success_rate = success_count as f64 / total as f64;

                let avg_latency =
                    group.iter().map(|t| t.tool_execution_ms).sum::<i64>() as f64 / total as f64;

                let mut intents: Vec<String> = group
                    .iter()
                    .map(|t| t.intent_type.clone())
                    .collect::<std::collections::HashSet<_>>()
                    .into_iter()
                    .collect();
                intents.sort();

                ToolPattern {
                    tool_name,
                    total_uses: total,
                    success_count,
                    failure_count,
                    success_rate,
                    used_by_intents: intents,
                    avg_latency_ms: avg_latency,
                }
            })
            .collect()
    }

    // ── Recommendation Generation ──────────────────────────────────────

    fn generate_recommendations(
        &self,
        intent_stats: &[IntentStats],
        tool_patterns: &[ToolPattern],
    ) -> Vec<Recommendation> {
        let mut recommendations = Vec::new();

        // 1. Critical: Intents with very low success rates
        for stats in intent_stats {
            if stats.success_rate < self.critical_success_threshold && stats.total_runs >= 20 {
                recommendations.push(Recommendation {
                    id: Uuid::new_v4().to_string(),
                    recommendation_type: RecommendationType::IntentWeightAdjustment,
                    priority: RecommendationPriority::Critical,
                    description: format!(
                        "Intent '{}' has {:.0}% success rate ({} runs). \
                         Consider adding more pattern keywords or adjusting tool selection.",
                        stats.intent_type,
                        stats.success_rate * 100.0,
                        stats.total_runs
                    ),
                    target: format!("intent:{}", stats.intent_type),
                    current_value: serde_json::json!({
                        "success_rate": stats.success_rate,
                        "primary_tier": stats.primary_tier,
                    }),
                    recommended_value: serde_json::json!({
                        "action": "boost_pattern_keywords",
                        "boost_tier1_confidence": true,
                        "review_tool_selection": true,
                    }),
                    confidence: 0.9,
                    expected_improvement: "success_rate +10-20%".to_string(),
                    evidence: vec![
                        format!("{} runs, {:.0}% success", stats.total_runs, stats.success_rate * 100.0),
                        format!("avg confidence: {:.2}", stats.avg_confidence),
                        format!("{} corrections ({:.0}%)", stats.correction_count, stats.correction_rate * 100.0),
                    ],
                    created_at: Utc::now(),
                });
            }
        }

        // 2. High: Intents with high correction rates
        for stats in intent_stats {
            if stats.correction_rate > self.correction_threshold && stats.total_runs >= 10 {
                recommendations.push(Recommendation {
                    id: Uuid::new_v4().to_string(),
                    recommendation_type: RecommendationType::PatternKeywordAddition,
                    priority: RecommendationPriority::High,
                    description: format!(
                        "Intent '{}' has {:.0}% correction rate — users often rephrase. \
                         The router may be misclassifying this intent.",
                        stats.intent_type,
                        stats.correction_rate * 100.0
                    ),
                    target: format!("intent:{}", stats.intent_type),
                    current_value: serde_json::json!({
                        "correction_rate": stats.correction_rate,
                        "corrections": stats.correction_count,
                    }),
                    recommended_value: serde_json::json!({
                        "action": "add_pattern_keywords",
                        "analyze_correction_inputs": true,
                    }),
                    confidence: 0.85,
                    expected_improvement: "correction_rate -10-15%".to_string(),
                    evidence: vec![
                        format!("{} corrections out of {} runs", stats.correction_count, stats.total_runs),
                        format!("primary tier: {}", stats.primary_tier),
                    ],
                    created_at: Utc::now(),
                });
            }
        }

        // 3. Tool failure patterns
        for tool in tool_patterns {
            if tool.success_rate < 0.70 && tool.total_uses >= 20 {
                recommendations.push(Recommendation {
                    id: Uuid::new_v4().to_string(),
                    recommendation_type: RecommendationType::ToolRemoval,
                    priority: RecommendationPriority::High,
                    description: format!(
                        "Tool '{}' has {:.0}% success rate across {} uses (intents: {}). \
                         Consider removing from low-performing intents or fixing the tool.",
                        tool.tool_name,
                        tool.success_rate * 100.0,
                        tool.total_uses,
                        tool.used_by_intents.join(", ")
                    ),
                    target: format!("tool:{}", tool.tool_name),
                    current_value: serde_json::json!({
                        "success_rate": tool.success_rate,
                        "total_uses": tool.total_uses,
                    }),
                    recommended_value: serde_json::json!({
                        "action": "review_tool_implementation",
                        "consider_alternatives": true,
                    }),
                    confidence: 0.8,
                    expected_improvement: "tool_success_rate +15-25%".to_string(),
                    evidence: vec![
                        format!("{} uses, {:.0}% success", tool.total_uses, tool.success_rate * 100.0),
                        format!("avg latency: {:.0}ms", tool.avg_latency_ms),
                    ],
                    created_at: Utc::now(),
                });
            }
        }

        // 4. Tier escalation: intents mostly resolved by LLM (Tier 3)
        for stats in intent_stats {
            let llm_count = stats.tier_distribution.get("LLM").unwrap_or(&0);
            let llm_pct = *llm_count as f64 / stats.total_runs as f64;
            if llm_pct > 0.5 && stats.total_runs >= 20 {
                recommendations.push(Recommendation {
                    id: Uuid::new_v4().to_string(),
                    recommendation_type: RecommendationType::TierThresholdChange,
                    priority: RecommendationPriority::Medium,
                    description: format!(
                        "Intent '{}' is resolved by LLM (Tier 3) {:.0}% of the time. \
                         Add more pattern keywords or embedding exemplars to reduce LLM dependency.",
                        stats.intent_type,
                        llm_pct * 100.0
                    ),
                    target: format!("intent:{}", stats.intent_type),
                    current_value: serde_json::json!({
                        "tier_distribution": stats.tier_distribution,
                    }),
                    recommended_value: serde_json::json!({
                        "action": "add_tier1_and_tier2_patterns",
                        "reduce_llm_escalation": true,
                    }),
                    confidence: 0.75,
                    expected_improvement: "latency -30-50%, cost reduction".to_string(),
                    evidence: vec![
                        format!("{:.0}% LLM resolution", llm_pct * 100.0),
                        format!("avg latency: {:.0}ms", stats.avg_latency_ms),
                    ],
                    created_at: Utc::now(),
                });
            }
        }

        // 5. Context assembly: intents with low confidence but high success
        for stats in intent_stats {
            if stats.avg_confidence < 0.6 && stats.success_rate > 0.8 && stats.total_runs >= 20 {
                recommendations.push(Recommendation {
                    id: Uuid::new_v4().to_string(),
                    recommendation_type: RecommendationType::ContextPriorityChange,
                    priority: RecommendationPriority::Low,
                    description: format!(
                        "Intent '{}' succeeds {:.0}% but avg confidence is only {:.2}. \
                         Context assembly may not be providing enough relevant signals.",
                        stats.intent_type,
                        stats.success_rate * 100.0,
                        stats.avg_confidence
                    ),
                    target: format!("context:{}", stats.intent_type),
                    current_value: serde_json::json!({
                        "avg_confidence": stats.avg_confidence,
                        "success_rate": stats.success_rate,
                    }),
                    recommended_value: serde_json::json!({
                        "action": "enrich_context_for_intent",
                        "add_flywheel_insights": true,
                    }),
                    confidence: 0.7,
                    expected_improvement: "confidence +0.1-0.2".to_string(),
                    evidence: vec![
                        format!("avg confidence: {:.2}, success rate: {:.0}%", stats.avg_confidence, stats.success_rate * 100.0),
                    ],
                    created_at: Utc::now(),
                });
            }
        }

        // Sort by priority (critical first)
        recommendations.sort_by(|a, b| b.priority.cmp(&a.priority));
        recommendations
    }

    // ── Report Storage ─────────────────────────────────────────────────

    /// Store an analysis report in the database.
    pub async fn store_report(&self, report: &AnalysisReport) -> anyhow::Result<()> {
        sqlx::query(
            r#"
            INSERT INTO trace_analysis_reports (
                report_id, window_start, window_end, total_traces,
                intent_stats, tool_patterns, recommendations, generated_at
            ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
            ON CONFLICT (report_id) DO NOTHING
            "#,
        )
        .bind(&report.report_id)
        .bind(report.analysis_window_start)
        .bind(report.analysis_window_end)
        .bind(report.total_traces_analyzed)
        .bind(serde_json::to_value(&report.intent_stats)?)
        .bind(serde_json::to_value(&report.tool_patterns)?)
        .bind(serde_json::to_value(&report.recommendations)?)
        .bind(report.generated_at)
        .execute(&self.db)
        .await?;

        info!("TraceAnalyzer: report {} stored", report.report_id);
        Ok(())
    }

    /// Get the most recent analysis report.
    pub async fn get_latest_report(&self) -> anyhow::Result<Option<AnalysisReport>> {
        let row: Option<(String, DateTime<Utc>, DateTime<Utc>, i64, serde_json::Value, serde_json::Value, serde_json::Value, DateTime<Utc>)> =
            sqlx::query_as(
                r#"
                SELECT report_id, window_start, window_end, total_traces,
                       intent_stats, tool_patterns, recommendations, generated_at
                FROM trace_analysis_reports
                ORDER BY generated_at DESC
                LIMIT 1
                "#,
            )
            .fetch_optional(&self.db)
            .await?;

        Ok(row.map(|r| AnalysisReport {
            report_id: r.0,
            analysis_window_start: r.1,
            analysis_window_end: r.2,
            total_traces_analyzed: r.3,
            intent_stats: serde_json::from_value(r.4).unwrap_or_default(),
            tool_patterns: serde_json::from_value(r.5).unwrap_or_default(),
            recommendations: serde_json::from_value(r.6).unwrap_or_default(),
            generated_at: r.7,
        }))
    }
}

// ─── Migration SQL ──────────────────────────────────────────────────────

pub const CREATE_REPORTS_TABLE: &str = r#"
CREATE TABLE IF NOT EXISTS trace_analysis_reports (
    report_id TEXT PRIMARY KEY,
    window_start TIMESTAMPTZ NOT NULL,
    window_end TIMESTAMPTZ NOT NULL,
    total_traces BIGINT NOT NULL,
    intent_stats JSONB NOT NULL DEFAULT '[]',
    tool_patterns JSONB NOT NULL DEFAULT '[]',
    recommendations JSONB NOT NULL DEFAULT '[]',
    generated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_trace_reports_generated ON trace_analysis_reports(generated_at);
"#;

// ─── Tests ──────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_recommendation_priority_ordering() {
        let mut recs = vec![
            RecommendationPriority::Low,
            RecommendationPriority::Critical,
            RecommendationPriority::Medium,
            RecommendationPriority::High,
        ];
        recs.sort();
        assert_eq!(recs[0], RecommendationPriority::Low);
        assert_eq!(recs[3], RecommendationPriority::Critical);
    }

    #[test]
    fn test_intent_stats_success_rate() {
        let stats = IntentStats {
            intent_type: "RECORD_SALE".to_string(),
            total_runs: 100,
            success_count: 75,
            failure_count: 25,
            success_rate: 0.75,
            avg_confidence: 0.82,
            avg_latency_ms: 1500.0,
            correction_count: 10,
            correction_rate: 0.10,
            positive_feedback: 60,
            negative_feedback: 15,
            feedback_rate: 0.80,
            primary_tier: "PATTERN".to_string(),
            tier_distribution: HashMap::new(),
        };
        assert_eq!(stats.success_rate, 0.75);
        assert_eq!(stats.correction_rate, 0.10);
    }
}
