"""Initial migration — create all tables.

Revision ID: 001_initial
Revises: None
Create Date: 2026-07-04

This migration creates the initial schema for Angavu Intelligence.
It is auto-generated from the SQLAlchemy ORM models.

To generate a fresh migration from current models:
    cd biashara-intelligence-backend
    alembic -c alembic.ini revision --autogenerate -m "initial"

To apply:
    alembic -c alembic.ini upgrade head

To rollback:
    alembic -c alembic.ini downgrade -1
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers
revision: str = "001_initial"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create all tables from ORM models.

    NOTE: This is a placeholder migration. Run `alembic revision --autogenerate`
    to generate the actual schema from current models, then replace this file.
    """
    # The actual table creation will be auto-generated by Alembic when you run:
    #   alembic -c alembic.ini revision --autogenerate -m "create_initial_tables"
    #
    # Key tables (from app/models/):
    #   - users (User)
    #   - transactions (Transaction)
    #   - inventory (Inventory)
    #   - buyers (Buyer)
    #   - buyer_api_keys (BuyerAPIKey)
    #   - intelligence_products (IntelligenceProduct)
    #   - data_access_logs (DataAccessLog)
    #   - soko_pulse_reports (SokoPulseReport)
    #   - biashara_pulse_reports (BiasharaPulseReport)
    #   - alama_scores (AlamaScore)
    #   - jamii_insights_reports (JamiiInsightsReport)
    #   - tax_base_estimations (TaxBaseEstimation)
    #   - distribution_gap_reports (DistributionGapReport)
    #   - tithe_records (TitheRecord)
    #   - goals (Goal)
    #   - loans (Loan)
    #   - mindset_lessons (MindsetLesson)
    #   - agent_configs (AgentConfig)
    #   - server_metrics (ServerMetric)
    #   - model_versions (ModelVersion)
    #   - invoices (InvoiceDB)
    #   - leads (LeadDB)
    #   - onboarding_flows (OnboardingFlowDB)
    pass


def downgrade() -> None:
    """Drop all tables."""
    pass
