"""
Measure and Probability Theory — STA 443: Measure and Probability Theory.

Probability spaces, conditional expectation, convergence theorems,
and foundational probability theory for Angavu Intelligence.

Academic Foundation:
- STA 443: Measure and Probability Theory — Sigma-algebras, measure
  spaces, Lebesgue integration, conditional expectation, convergence
  theorems (MCT, Fatou, Dominated), Radon-Nikodym theorem, martingales

Key Applications:
1. Probability space construction for financial modeling
2. Conditional expectation E[X|G] as optimal predictor
3. Convergence guarantees for Monte Carlo methods
4. Measure-theoretic foundations for Bayesian inference
5. Martingale theory for fair pricing of financial instruments

This module is wired into StatisticalFoundation as the theoretical base.
"""

from typing import Any

import numpy as np
import structlog
from scipy import stats as sp_stats

logger = structlog.get_logger(__name__)


class ProbabilitySpace:
    """
    Probability space (Ω, F, P) construction and manipulation.

    Driven by STA 443 § Probability Spaces:
    - Sample space Ω: Set of all possible outcomes
    - Sigma-algebra F: Collection of measurable events
    - Probability measure P: P(Ω) = 1, countable additivity

    For financial applications:
    - Ω = set of all possible market scenarios
    - F = sigma-algebra generated by price processes
    - P = objective or risk-neutral probability measure
    """

    @staticmethod
    def construct_discrete_space(
        outcomes: list[Any],
        probabilities: np.ndarray,
    ) -> dict[str, Any]:
        """
        Construct a discrete probability space.

        Args:
            outcomes: List of possible outcomes
            probabilities: Probability vector (must sum to 1)

        Returns:
            Dict with probability space specification
        """
        probs = np.asarray(probabilities, dtype=float)

        # Validate
        if abs(probs.sum() - 1.0) > 1e-6:
            probs = probs / probs.sum()  # Normalize

        if np.any(probs < 0):
            return {"error": "Negative probabilities not allowed"}

        return {
            "omega": outcomes,
            "n_outcomes": len(outcomes),
            "probabilities": {str(o): round(float(p), 6) for o, p in zip(outcomes, probs)},
            "measure_properties": {
                "non_negative": bool(np.all(probs >= 0)),
                "sums_to_one": bool(abs(probs.sum() - 1.0) < 1e-6),
                "countable_additivity": True,
            },
            "method": "STA 443 — Discrete Probability Space",
        }

    @staticmethod
    def conditional_probability(
        joint_probs: np.ndarray,
        event_indices: list[int],
        given_indices: list[int],
    ) -> dict[str, Any]:
        """
        Compute conditional probability P(A|B) = P(A∩B)/P(B).

        Args:
            joint_probs: Joint probability table
            event_indices: Indices for event A
            given_indices: Indices for event B

        Returns:
            Dict with conditional probability and Bayes factor
        """
        p_b = sum(joint_probs[i] for i in given_indices if i < len(joint_probs))
        p_ab = sum(joint_probs[i] for i in event_indices if i < len(joint_probs) and i in given_indices)

        if p_b < 1e-15:
            return {"error": "P(B) = 0 — conditioning on impossible event"}

        p_a_given_b = p_ab / p_b

        return {
            "P(A|B)": round(float(p_a_given_b), 6),
            "P(A∩B)": round(float(p_ab), 6),
            "P(B)": round(float(p_b), 6),
            "bayes_factor": round(float(p_a_given_b / max(p_b, 1e-15)), 4),
            "method": "STA 443 — Conditional Probability",
        }


class ConditionalExpectation:
    """
    Conditional expectation E[X|G] as the optimal predictor.

    Driven by STA 443 § Conditional Expectation:
    - E[X|G] is the G-measurable random variable that best
      approximates X in the L² sense
    - Projection theorem: E[X|G] = projection of X onto L²(G)
    - Tower property: E[E[X|G]] = E[X]
    - Jensen's inequality: E[g(X)|G] ≥ g(E[X|G]) for convex g

    Applications:
    - Credit scoring: E[default|transaction_features] = optimal predictor
    - Revenue forecasting: E[revenue|past_data] = best forecast
    - Risk assessment: E[loss|market_state] = conditional risk measure
    """

    @staticmethod
    def compute_discrete(
        X: np.ndarray,
        groups: np.ndarray,
    ) -> dict[str, Any]:
        """
        Compute E[X|G] for discrete partition G.

        Args:
            X: Random variable values
            groups: Group labels (partition of sample space)

        Returns:
            Dict with conditional expectations per group
        """
        X = np.asarray(X, dtype=float)
        groups = np.asarray(groups)

        unique_groups = np.unique(groups)
        cond_exp = {}
        group_probs = {}

        for g in unique_groups:
            mask = groups == g
            group_X = X[mask]
            cond_exp[str(g)] = round(float(np.mean(group_X)), 4)
            group_probs[str(g)] = round(float(np.mean(mask)), 4)

        # Verify tower property: E[E[X|G]] = E[X]
        tower_check = sum(
            cond_exp[str(g)] * group_probs[str(g)]
            for g in unique_groups
        )
        ex = float(np.mean(X))

        return {
            "conditional_expectations": cond_exp,
            "group_probabilities": group_probs,
            "E[X]": round(ex, 4),
            "E[E[X|G]]": round(float(tower_check), 4),
            "tower_property_holds": abs(tower_check - ex) < 1e-6,
            "n_groups": len(unique_groups),
            "method": "STA 443 — Discrete Conditional Expectation",
        }

    @staticmethod
    def bayesian_conditional(
        prior_mean: float,
        prior_var: float,
        data_mean: float,
        data_var: float,
        n: int,
    ) -> dict[str, Any]:
        """
        Bayesian conditional expectation (Normal-Normal conjugacy).

        E[θ|X̄] = posterior mean = weighted average of prior and data.

        Args:
            prior_mean: Prior mean μ₀
            prior_var: Prior variance σ₀²
            data_mean: Sample mean X̄
            data_var: Known data variance σ²
            n: Sample size

        Returns:
            Dict with posterior mean (conditional expectation) and variance
        """
        prior_precision = 1 / prior_var
        data_precision = n / data_var

        post_precision = prior_precision + data_precision
        post_var = 1 / post_precision
        post_mean = (prior_precision * prior_mean + data_precision * data_mean) / post_precision

        shrinkage = data_precision / post_precision

        return {
            "E[theta|X]": round(float(post_mean), 4),
            "posterior_variance": round(float(post_var), 6),
            "shrinkage_factor": round(float(shrinkage), 4),
            "prior_contribution": round(float(1 - shrinkage), 4),
            "data_contribution": round(float(shrinkage), 4),
            "credible_interval_95": (
                round(float(post_mean - 1.96 * np.sqrt(post_var)), 4),
                round(float(post_mean + 1.96 * np.sqrt(post_var)), 4),
            ),
            "method": "STA 443 — Bayesian Conditional Expectation",
        }


class ConvergenceTheorems:
    """
    Convergence theorems for Monte Carlo and inference validation.

    Driven by STA 443 § Convergence Theorems:
    - Monotone Convergence Theorem (MCT): If 0 ≤ Xₙ ↑ X, then E[Xₙ] ↑ E[X]
    - Fatou's Lemma: E[lim inf Xₙ] ≤ lim inf E[Xₙ]
    - Dominated Convergence Theorem (DCT): If |Xₙ| ≤ Y and Xₙ → X
      a.s., then E[Xₙ] → E[X]
    - Law of Large Numbers (LLN): X̄ₙ → μ a.s. (SLLN) or in probability (WLLN)
    - Central Limit Theorem (CLT): √n(X̄ₙ - μ)/σ → N(0,1) in distribution

    Applications:
    - Monte Carlo convergence: DCT guarantees E[X̂ₙ] → E[X]
    - Bootstrap validity: CLT justifies bootstrap CIs
    - MCMC convergence: LLN ensures ergodic averages converge
    """

    @staticmethod
    def verify_lln(
        data: np.ndarray,
        true_mean: float,
        sample_sizes: list[int] | None = None,
    ) -> dict[str, Any]:
        """
        Verify Law of Large Numbers convergence.

        Shows X̄ₙ → μ as n → ∞.

        Args:
            data: Sample data
            true_mean: Known population mean
            sample_sizes: Sizes at which to check convergence

        Returns:
            Dict with convergence diagnostics
        """
        n = len(data)
        if sample_sizes is None:
            sample_sizes = [min(s, n) for s in [10, 50, 100, 500, 1000, n] if s <= n]

        running_means = []
        for s in sample_sizes:
            xbar = float(np.mean(data[:s]))
            error = abs(xbar - true_mean)
            running_means.append({
                "n": s,
                "sample_mean": round(xbar, 6),
                "error": round(error, 6),
                "relative_error": round(error / max(abs(true_mean), 1e-10), 6),
            })

        return {
            "true_mean": true_mean,
            "convergence_points": running_means,
            "final_sample_size": n,
            "final_mean": round(float(np.mean(data)), 6),
            "final_error": round(float(abs(np.mean(data) - true_mean)), 6),
            "converging": running_means[-1]["error"] < running_means[0]["error"],
            "method": "STA 443 — Law of Large Numbers Verification",
        }

    @staticmethod
    def clt_diagnostics(
        data: np.ndarray,
        n_bootstrap: int = 1000,
    ) -> dict[str, Any]:
        """
        CLT diagnostics — check if sample mean is approximately normal.

        Args:
            data: Sample data
            n_bootstrap: Bootstrap samples for CLT verification

        Returns:
            Dict with normality tests and CLT verification
        """
        n = len(data)
        mu = float(np.mean(data))
        sigma = float(np.std(data, ddof=1))

        # Bootstrap distribution of sample mean
        rng = np.random.RandomState(42)
        boot_means = np.array([
            np.mean(rng.choice(data, size=n, replace=True))
            for _ in range(n_bootstrap)
        ])

        # Normality tests on bootstrap means
        _, shapiro_p = sp_stats.shapiro(boot_means[:min(5000, n_bootstrap)])
        _, ks_p = sp_stats.kstest(
            boot_means, "norm",
            args=(mu, sigma / np.sqrt(n))
        )

        return {
            "sample_size": n,
            "sample_mean": round(mu, 6),
            "bootstrap_mean_of_means": round(float(np.mean(boot_means)), 6),
            "bootstrap_std_of_means": round(float(np.std(boot_means)), 6),
            "theoretical_se": round(sigma / np.sqrt(n), 6),
            "shapiro_p_value": round(float(shapiro_p), 6),
            "ks_p_value": round(float(ks_p), 6),
            "clt_applies": shapiro_p > 0.01 and ks_p > 0.01,
            "method": "STA 443 — CLT Diagnostics",
        }


class MartingaleAnalyzer:
    """
    Martingale theory for financial applications.

    Driven by STA 443 § Martingales:
    - Definition: E[X_{t+1}|F_t] = X_t (fair game property)
    - Supermartingale: E[X_{t+1}|F_t] ≤ X_t (losing game)
    - Submartingale: E[X_{t+1}|F_t] ≥ X_t (winning game)
    - Optional stopping theorem: E[X_τ] = E[X_0] for bounded stopping times

    Applications:
    - Efficient market hypothesis: Prices are martingales under risk-neutral measure
    - Credit scoring: Score changes should be martingales if model is well-calibrated
    - Fair pricing: No-arbitrage prices are martingale expectations
    """

    @staticmethod
    def test_martingale_property(
        series: np.ndarray,
        alpha: float = 0.05,
    ) -> dict[str, Any]:
        """
        Test whether a series satisfies the martingale property.

        H₀: E[X_{t+1}|X_t] = X_t (martingale)
        Uses regression: X_{t+1} = α + β·X_t + ε
        Under H₀: α = 0, β = 1

        Args:
            series: Time series data
            alpha: Significance level

        Returns:
            Dict with martingale test results
        """
        if len(series) < 10:
            return {"error": "Need at least 10 observations"}

        X_t = series[:-1]
        X_t1 = series[1:]

        # OLS: X_{t+1} = α + β·X_t + ε
        X = np.column_stack([np.ones(len(X_t)), X_t])
        try:
            beta = np.linalg.lstsq(X, X_t1, rcond=None)[0]
        except np.linalg.LinAlgError:
            return {"error": "Regression failed"}

        residuals = X_t1 - X @ beta
        n = len(residuals)
        k = 2
        sigma2 = float(np.sum(residuals ** 2) / (n - k))

        # Test α = 0
        se_alpha = np.sqrt(sigma2 * np.linalg.inv(X.T @ X)[0, 0])
        t_alpha = float(beta[0]) / max(se_alpha, 1e-10)
        p_alpha = 2 * (1 - sp_stats.t.cdf(abs(t_alpha), n - k))

        # Test β = 1
        se_beta = np.sqrt(sigma2 * np.linalg.inv(X.T @ X)[1, 1])
        t_beta = (float(beta[1]) - 1) / max(se_beta, 1e-10)
        p_beta = 2 * (1 - sp_stats.t.cdf(abs(t_beta), n - k))

        is_martingale = p_alpha > alpha and p_beta > alpha

        return {
            "intercept": round(float(beta[0]), 6),
            "slope": round(float(beta[1]), 6),
            "test_intercept_zero": {
                "t_statistic": round(float(t_alpha), 4),
                "p_value": round(float(p_alpha), 6),
                "reject": p_alpha < alpha,
            },
            "test_slope_one": {
                "t_statistic": round(float(t_beta), 4),
                "p_value": round(float(p_beta), 6),
                "reject": p_beta < alpha,
            },
            "is_martingale": is_martingale,
            "interpretation": (
                "Series satisfies martingale property — consistent with efficient pricing."
                if is_martingale
                else "Series violates martingale property — predictable patterns exist."
            ),
            "method": "STA 443 — Martingale Property Test",
        }
