"""
Agent-related data models for the multi-agent architecture.

Defines:
    - WorkerType: Enum of supported worker types
    - AgentConfig: Configuration for domain agents
    - AgentInsight: Intelligence output from agents
    - AgentRecommendation: Actionable recommendation from agents

These are Pydantic models for API serialization, not ORM models.
"""

from __future__ import annotations

from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Optional
from uuid import UUID, uuid4

from pydantic import BaseModel, Field


# ── Worker Types ────────────────────────────────────────────────────

class WorkerType(str, Enum):
    """Supported informal worker types."""
    TRANSPORT = "transport"
    TRADER = "trader"
    AGRICULTURE = "agriculture"
    SERVICE = "service"
    DIGITAL = "digital"
    MANUFACTURING = "manufacturing"
    GENERAL = "general"


# ── Agent Configuration ─────────────────────────────────────────────

class AgentConfig(BaseModel):
    """Configuration for a domain agent."""
    agent_name: str = Field(..., description="Agent name (e.g., TransportAgent)")
    worker_type: WorkerType = Field(..., description="Worker type this agent serves")
    tier: int = Field(..., ge=1, le=3, description="Agent tier (1=Core, 2=Domain, 3=Utility)")
    capabilities: List[str] = Field(default_factory=list, description="Agent capabilities")
    is_active: bool = Field(default=True, description="Whether agent is active")
    version: str = Field(default="1.0.0", description="Agent version")


# ── Agent Insights ──────────────────────────────────────────────────

class AgentInsight(BaseModel):
    """
    Intelligence output from a domain agent.

    Represents a single insight (analytical finding) generated
    by processing worker transaction data.
    """
    id: str = Field(default_factory=lambda: uuid4().hex[:16], description="Insight ID")
    agent_name: str = Field(..., description="Which agent generated this")
    worker_type: WorkerType = Field(..., description="Worker type context")
    category: str = Field(..., description="Insight category (e.g., fuel_efficiency, spoilage)")
    title: str = Field(..., description="Short insight title")
    value: Any = Field(..., description="Insight value (number, string, dict)")
    metric: Optional[str] = Field(None, description="Unit of measurement")
    trend: Optional[str] = Field(None, description="Trend direction: up, down, stable")
    period_days: int = Field(default=30, description="Analysis period in days")
    timestamp: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="When insight was generated",
    )

    class Config:
        json_encoders = {
            datetime: lambda v: v.isoformat(),
        }


# ── Agent Recommendations ───────────────────────────────────────────

class AgentRecommendation(BaseModel):
    """
    Actionable recommendation from a domain agent.

    Represents advice generated by a domain agent based on
    analysis of worker transaction data.
    """
    id: str = Field(default_factory=lambda: uuid4().hex[:16], description="Recommendation ID")
    agent_name: str = Field(..., description="Which agent generated this")
    worker_type: WorkerType = Field(..., description="Worker type context")
    category: str = Field(..., description="Recommendation category")
    title: str = Field(..., description="Short title")
    message: str = Field(..., description="Detailed recommendation message")
    priority: str = Field(
        default="medium",
        description="Priority level: low, medium, high",
    )
    language: str = Field(default="en", description="Language: en or sw")
    timestamp: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="When recommendation was generated",
    )

    class Config:
        json_encoders = {
            datetime: lambda v: v.isoformat(),
        }


# ── API Request/Response Models ─────────────────────────────────────

class ClassifyRequest(BaseModel):
    """Request to classify a worker's type."""
    user_id: str = Field(..., description="User ID to classify")
    transactions: Optional[List[Dict[str, Any]]] = Field(
        None,
        description="Transaction data (if not fetching from DB)",
    )


class ClassifyResponse(BaseModel):
    """Response from worker classification."""
    user_id: str
    primary_type: WorkerType
    types: List[Dict[str, Any]] = Field(
        ...,
        description="List of {type, confidence, evidence}",
    )
    is_multi_type: bool


class InsightsResponse(BaseModel):
    """Response containing domain agent insights."""
    user_id: str
    worker_type: WorkerType
    agent_name: str
    period_days: int
    insights: List[AgentInsight]
    analysis: Dict[str, Any] = Field(
        default_factory=dict,
        description="Raw analysis data",
    )


class RecommendationsResponse(BaseModel):
    """Response containing domain agent recommendations."""
    user_id: str
    worker_type: WorkerType
    agent_name: str
    recommendations: List[AgentRecommendation]
    language: str = "en"
