"""
Intelligence product and data access log models.

IntelligenceProducts are pre-computed data products sold to buyers.
DataAccessLog tracks every query a buyer makes for audit compliance.
"""

import uuid
from datetime import datetime, timezone

from sqlalchemy import (
    Column,
    DateTime,
    Enum,
    Float,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
)
from sqlalchemy.dialects.postgresql import JSON, UUID

from app.db.database import Base


class IntelligenceProduct(Base):
    """
    A pre-computed intelligence product available for purchase.

    Products are generated by the data pipeline and include things like:
    - Market-level demand forecasts
    - Regional economic activity indices
    - Product pricing intelligence
    - Distribution gap analyses

    Attributes:
        id: UUID primary key
        buyer_id: Foreign key to the buyer who purchased this
        product_type: Type of intelligence product
        market_id: Geographic market identifier (geohash-5 or county code)
        region: Human-readable region name
        product_name: Specific product this intelligence covers (or 'all')
        time_period: Time period covered (e.g., '2026-W26', '2026-06')
        granularity: Data granularity level
        data: The actual intelligence payload (JSON)
        metadata_extra: Additional metadata
        price_kes: Price charged in KES
        users_included: Number of users whose data contributed
        k_anonymity_value: Actual k value achieved
        quality_score: Overall data quality score (0-1)
        status: Product generation status
        created_at: When the product was generated
        expires_at: When the product expires
    """

    __tablename__ = "intelligence_products"

    id = Column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )
    buyer_id = Column(
        UUID(as_uuid=True),
        ForeignKey("buyers.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    product_type = Column(
        Enum(
            "market_demand", "price_intelligence", "distribution_gap",
            "economic_activity", "credit_signal", "custom_report",
            name="product_type_enum",
        ),
        nullable=False,
        index=True,
    )
    market_id = Column(
        String(20),
        nullable=True,
        index=True,
        doc="Geographic market ID (geohash-5 or county code)",
    )
    region = Column(
        String(100),
        nullable=True,
        doc="Human-readable region name",
    )
    product_name = Column(
        String(200),
        nullable=True,
        default="all",
        doc="Specific product or 'all' for general intelligence",
    )
    time_period = Column(
        String(20),
        nullable=True,
        doc="Time period: '2026-W26', '2026-06', '2026-Q2'",
    )
    granularity = Column(
        Enum(
            "individual", "micro_market", "county", "national",
            name="granularity_enum",
        ),
        nullable=False,
        default="micro_market",
    )
    data = Column(
        JSON,
        nullable=False,
        doc="Intelligence payload as JSON",
    )
    metadata_extra = Column(
        JSON,
        nullable=True,
        doc="Additional metadata (filters, methodology, etc.)",
    )
    price_kes = Column(
        Float,
        nullable=True,
        default=0,
        doc="Price charged for this product in KES",
    )
    users_included = Column(
        Integer,
        nullable=True,
        doc="Number of users whose data contributed",
    )
    k_anonymity_value = Column(
        Integer,
        nullable=True,
        doc="Actual k-anonymity value achieved (must be >= K_ANONYMITY_THRESHOLD)",
    )
    quality_score = Column(
        Float,
        nullable=True,
        doc="Overall data quality score 0-1",
    )
    status = Column(
        Enum(
            "pending", "processing", "ready", "delivered", "expired",
            name="product_status_enum",
        ),
        nullable=False,
        default="pending",
        index=True,
    )
    created_at = Column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
    )
    expires_at = Column(
        DateTime(timezone=True),
        nullable=True,
        doc="When this intelligence product expires and should be purged",
    )

    __table_args__ = (
        Index("idx_intel_market_period", "market_id", "time_period"),
        Index("idx_intel_type_status", "product_type", "status"),
        Index("idx_intel_created", "created_at"),
    )

    def __repr__(self) -> str:
        return (
            f"<IntelligenceProduct {self.product_type} "
            f"market={self.market_id} status={self.status}>"
        )

    @property
    def is_expired(self) -> bool:
        """Check if this product has expired."""
        if self.expires_at is None:
            return False
        return datetime.now(timezone.utc) > self.expires_at


class DataAccessLog(Base):
    """
    Audit log for all data access by buyers.

    Every time a buyer queries the intelligence API, a log entry is created.
    This is critical for regulatory compliance (Kenya Data Protection Act 2019)
    and for tracking buyer engagement.

    Attributes:
        id: UUID primary key
        buyer_id: Who accessed the data
        api_key_id: Which API key was used
        endpoint: API endpoint called
        query_params: Query parameters (sanitized — no PII)
        response_size_bytes: Size of response
        records_returned: Number of records in response
        processing_time_ms: How long the query took
        ip_address: Client IP (for security)
        user_agent: Client user agent
        status_code: HTTP response status
        error_message: Error details if failed
        accessed_at: When the access happened
    """

    __tablename__ = "data_access_logs"

    id = Column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )
    buyer_id = Column(
        UUID(as_uuid=True),
        ForeignKey("buyers.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    api_key_id = Column(
        UUID(as_uuid=True),
        ForeignKey("buyer_api_keys.id", ondelete="SET NULL"),
        nullable=True,
    )
    endpoint = Column(
        String(500),
        nullable=False,
        doc="API endpoint called",
    )
    query_params = Column(
        JSON,
        nullable=True,
        doc="Sanitized query parameters",
    )
    response_size_bytes = Column(
        Integer,
        nullable=True,
    )
    records_returned = Column(
        Integer,
        nullable=True,
    )
    processing_time_ms = Column(
        Float,
        nullable=True,
    )
    ip_address = Column(
        String(45),
        nullable=True,
        doc="Client IP address (IPv4 or IPv6)",
    )
    user_agent = Column(
        String(500),
        nullable=True,
    )
    status_code = Column(
        Integer,
        nullable=True,
    )
    error_message = Column(
        Text,
        nullable=True,
    )
    accessed_at = Column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        index=True,
    )

    __table_args__ = (
        Index("idx_dal_buyer_time", "buyer_id", "accessed_at"),
        Index("idx_dal_endpoint", "endpoint", "accessed_at"),
    )

    def __repr__(self) -> str:
        return f"<DataAccessLog {self.endpoint} buyer={self.buyer_id}>"
