"""
Intelligence Report Generator.

Generates formatted reports from intelligence product data.
Supports PDF and HTML output for all 6 products.

Report templates include:
- Executive summary
- Key metrics with visualizations
- Data methodology notes
- Privacy compliance statements
- Buyer-specific formatting
"""

from datetime import datetime, timezone
from typing import Any, Dict, List, Optional


# ════════════════════════════════════════════════════════════════════
# Swahili Translations — Report Labels & Section Headers
# ════════════════════════════════════════════════════════════════════

SWAHILI_TRANSLATIONS: Dict[str, Dict[str, str]] = {
    # Section headers
    "executive_summary": {"en": "Executive Summary", "sw": "Muhtasari wa Uongozi"},
    "demand_overview": {"en": "Demand Overview", "sw": "Muhtasari wa Mahitaji"},
    "price_intelligence": {"en": "Price Intelligence", "sw": "Ujasusi wa Bei"},
    "temporal_patterns": {"en": "Temporal Patterns", "sw": "Mifumo ya Muda"},
    "demand_forecast": {"en": "Demand Forecast", "sw": "Utabiri wa Mahitaji"},
    "methodology": {"en": "Methodology", "sw": "Mbinu za Uchunguzi"},
    "activity_indices": {"en": "Activity Indices", "sw": "Fahirisi za Shughuli"},
    "business_formation": {"en": "Business Formation", "sw": "Kuanzishwa kwa Biashara"},
    "sector_breakdown": {"en": "Sector Breakdown", "sw": "Mgawanyo wa Sekta"},
    "employment_estimates": {"en": "Employment Estimates", "sw": "Makadirio ya Ajira"},
    "county_comparison": {"en": "County Comparison", "sw": "Kulinganisha kwa Kaunti"},
    "score_overview": {"en": "Score Overview", "sw": "Muhtasari wa Alama"},
    "component_breakdown": {"en": "Component Breakdown", "sw": "Mgawanyo wa Vipengele"},
    "risk_assessment": {"en": "Risk Assessment", "sw": "Tathmini ya Hatari"},
    "peer_comparison": {"en": "Peer Comparison", "sw": "Kulinganisha kwa Wenzako"},
    "recommendation": {"en": "Recommendation", "sw": "Mapendekezo"},
    "inclusion_metrics": {"en": "Inclusion Metrics", "sw": "Vipimo vya Ujumuishaji"},
    "demographic_analysis": {"en": "Demographic Analysis", "sw": "Uchambuzi wa Idadi ya Watu"},
    "barrier_assessment": {"en": "Barrier Assessment", "sw": "Tathmini ya Vizuizi"},
    "program_impact": {"en": "Program Impact", "sw": "Athari za Programu"},
    "coverage_overview": {"en": "Coverage Overview", "sw": "Muhtasari wa Ufunikaji"},
    "gap_identification": {"en": "Gap Identification", "sw": "Kutambua Mapengo"},
    "opportunity_sizing": {"en": "Opportunity Sizing", "sw": "Kupima Fursa"},
    "competitive_landscape": {"en": "Competitive Landscape", "sw": "Mazingira ya Ushindani"},
    "expansion_recommendations": {"en": "Expansion Recommendations", "sw": "Mapendekezo ya Upanuzi"},
    "tax_base_overview": {"en": "Tax Base Overview", "sw": "Muhtasari wa Msingi wa Kodi"},
    "formalization_gap": {"en": "Formalization Gap", "sw": "Mpango wa Urasimishaji"},
    "revenue_projections": {"en": "Revenue Projections", "sw": "Makadirio ya Mapato"},
    "policy_recommendations": {"en": "Policy Recommendations", "sw": "Mapendekezo ya Sera"},
    # Metric labels
    "total_volume": {"en": "Total Volume", "sw": "Jumla ya Kiasi"},
    "avg_daily_volume": {"en": "Avg Daily Volume", "sw": "Wastani wa Kiasi cha Siku"},
    "demand_trend": {"en": "Demand Trend", "sw": "Mwelekeo wa Mahitaji"},
    "average_price": {"en": "Average Price", "sw": "Bei ya Wastani"},
    "price_range": {"en": "Price Range", "sw": "Mfumo wa Bei"},
    "alama_score": {"en": "Alama Score", "sw": "Alama ya Alama"},
    "score_band": {"en": "Score Band", "sw": "Kitengo cha Alama"},
    "percentile": {"en": "Percentile", "sw": "Asilimia"},
    "default_probability": {"en": "Default Probability", "sw": "Uwezekano wa Kushindwa Kulipa"},
    "credit_limit": {"en": "Credit Limit", "sw": "Kikomo cha Mkopo"},
    "activity_index": {"en": "Activity Index", "sw": "Fahirisi ya Shughuli"},
    "growth_index": {"en": "Growth Index", "sw": "Fahirisi ya Ukuaji"},
    "vendors": {"en": "Vendors", "sw": "Wachuuzi"},
    "businesses": {"en": "Businesses", "sw": "Biashara"},
    "regions": {"en": "Regions", "sw": "Mikoa"},
    # Trend labels
    "rising": {"en": "Rising", "sw": "Inapanda"},
    "declining": {"en": "Declining", "sw": "Inashuka"},
    "stable": {"en": "Stable", "sw": "Imara"},
    "growing": {"en": "Growing", "sw": "Inakua"},
    # Score bands
    "excellent": {"en": "Excellent", "sw": "Bora"},
    "good": {"en": "Good", "sw": "Nzuri"},
    "fair": {"en": "Fair", "sw": "Wastani"},
    "poor": {"en": "Poor", "sw": "Dhaifu"},
    "very_poor": {"en": "Very Poor", "sw": "Dhaifu Sana"},
    # Privacy
    "privacy_statement": {
        "en": "PRIVACY & DATA PROTECTION COMPLIANCE",
        "sw": "KUFUATANA NA ULINZI WA DATA",
    },
    "generated_by": {"en": "Generated by", "sw": "Imetolewa na"},
    "prepared_for": {"en": "Prepared for", "sw": "Imeandaliwa kwa"},
}


def get_translation(key: str, lang: str = "en") -> str:
    """Get translated label for a given key and language.

    Args:
        key: Translation key (e.g., 'demand_overview')
        lang: Language code ('en' or 'sw')

    Returns:
        Translated string, falling back to English if not found.
    """
    entry = SWAHILI_TRANSLATIONS.get(key, {})
    return entry.get(lang, entry.get("en", key))


# Report template definitions
REPORT_TEMPLATES = {
    "soko_pulse": {
        "title": "Soko Pulse — FMCG Demand Forecast Report",
        "sections": [
            "executive_summary",
            "demand_overview",
            "price_intelligence",
            "temporal_patterns",
            "demand_forecast",
            "methodology",
        ],
        "buyer_focus": "FMCG distribution optimization",
    },
    "biashara_pulse": {
        "title": "Angavu Pulse — MSME Activity Index Report",
        "sections": [
            "executive_summary",
            "activity_indices",
            "business_formation",
            "sector_breakdown",
            "employment_estimates",
            "county_comparison",
            "methodology",
        ],
        "buyer_focus": "Government economic policy",
    },
    "alama_score": {
        "title": "Alama Score — Credit Assessment Report",
        "sections": [
            "executive_summary",
            "score_overview",
            "component_breakdown",
            "risk_assessment",
            "peer_comparison",
            "recommendation",
            "methodology",
        ],
        "buyer_focus": "Credit decision support",
    },
    "jamii_insights": {
        "title": "Jamii Insights — Financial Inclusion Report",
        "sections": [
            "executive_summary",
            "inclusion_metrics",
            "demographic_analysis",
            "barrier_assessment",
            "program_impact",
            "recommendations",
            "methodology",
        ],
        "buyer_focus": "Development program evaluation",
    },
    "tax_base_estimation": {
        "title": "Tax Base Estimation — Revenue Intelligence Report",
        "sections": [
            "executive_summary",
            "tax_base_overview",
            "sector_analysis",
            "formalization_gap",
            "revenue_projections",
            "policy_recommendations",
            "methodology",
        ],
        "buyer_focus": "Government revenue optimization",
    },
    "distribution_gap": {
        "title": "Distribution Gap Analysis — Market Coverage Report",
        "sections": [
            "executive_summary",
            "coverage_overview",
            "gap_identification",
            "opportunity_sizing",
            "competitive_landscape",
            "expansion_recommendations",
            "methodology",
        ],
        "buyer_focus": "FMCG distribution expansion",
    },
}

# Privacy compliance statement (included in all reports)
# ════════════════════════════════════════════════════════════════════
# Swahili Translations for Report Templates
# ════════════════════════════════════════════════════════════════════

REPORT_TEMPLATES_SW = {
    "soko_pulse": {
        "title": "Soko Pulse — Ripoti ya Utabiri wa Mahitaji ya FMCG",
        "sections": [
            "muhtasari_wa_utendaji",
            "muhtasari_wa_mahitaji",
            "akili_ya_bei",
            "mifumo_ya_muda",
            "utabiri_wa_mahitaji",
            "mbinu_ya_utafiti",
        ],
        "buyer_focus": "Kuboresha usambazaji wa FMCG",
    },
    "biashara_pulse": {
        "title": "Angavu Pulse — Ripoti ya Kiashirio cha Shughuli za Biashara Ndogo",
        "sections": [
            "muhtasari_wa_utendaji",
            "viashirio_vya_shughuli",
            "kuundwa_kwa_biashara",
            "mgawanyo_wa_sekta",
            "makadirio_ya_ajira",
            "ulinganisho_wa_kunta",
            "mbinu_ya_utafiti",
        ],
        "buyer_focus": "Sera ya kiuchumi ya serikali",
    },
    "alama_score": {
        "title": "Alama Score — Ripoti ya Tathmini ya Mkopo",
        "sections": [
            "muhtasari_wa_utendaji",
            "muhtasari_wa_alama",
            "mgawanyo_wa_vipengele",
            "tathmini_ya_hatari",
            "ulinganisho_wa_wenzio",
            "mapendekezo",
            "mbinu_ya_utafiti",
        ],
        "buyer_focus": "Msaada wa uamuzi wa mkopo",
    },
    "jamii_insights": {
        "title": "Jamii Insights — Ripoti ya Ujumuishaji wa Kifedha",
        "sections": [
            "muhtasari_wa_utendaji",
            "vipimo_vya_ujumuishaji",
            "uchambuzi_wa_idadi_ya_watu",
            "tathmini_ya_vizuizi",
            "athari_ya_programu",
            "mapendekezo",
            "mbinu_ya_utafiti",
        ],
        "buyer_focus": "Tathmini ya programu ya maendeleo",
    },
}

# Section title translations (English → Swahili)
SECTION_TITLES_SW = {
    "executive_summary": "Muhtasari wa Utendaji",
    "demand_overview": "Muhtasari wa Mahitaji",
    "price_intelligence": "Akili ya Bei",
    "temporal_patterns": "Mifumo ya Muda",
    "demand_forecast": "Utabiri wa Mahitaji",
    "methodology": "Mbinu ya Utafiti",
    "activity_indices": "Viashirio vya Shughuli",
    "business_formation": "Kuundwa kwa Biashara",
    "sector_breakdown": "Mgawanyo wa Sekta",
    "employment_estimates": "Makadirio ya Ajira",
    "county_comparison": "Ulinganisho wa Kunta",
    "score_overview": "Muhtasari wa Alama",
    "component_breakdown": "Mgawanyo wa Vipengele",
    "risk_assessment": "Tathmini ya Hatari",
    "peer_comparison": "Ulinganisho wa Wenzio",
    "recommendation": "Mapendekezo",
    "inclusion_metrics": "Vipimo vya Ujumuishaji",
    "demographic_analysis": "Uchambuzi wa Idadi ya Watu",
    "barrier_assessment": "Tathmini ya Vizuizi",
    "program_impact": "Athari ya Programu",
    "recommendations": "Mapendekezo",
}

# Metric label translations
METRIC_LABELS_SW = {
    "Total Volume": "Jumla ya Kiasi",
    "Avg Daily Volume": "Wastani wa Kiasi cha Siku",
    "Vendors": "Wachuuzi",
    "Demand Trend": "Mwelekeo wa Mahitaji",
    "Average Price": "Wastani wa Bei",
    "Price Range": "Kipimo cha Bei",
    "Price Trend": "Mwelekeo wa Bei",
    "Forecasted Volume": "Kiasi kilichotabiriwa",
    "Activity Index (0-100)": "Kiashirio cha Shughuli (0-100)",
    "Growth Index (0-100)": "Kiashirio cha Ukuaji (0-100)",
    "Estimated Businesses": "Biashara Zinazokadiriwa",
    "M-Pesa Penetration": "Kuingia kwa M-Pesa",
    "Alama Score (300-850)": "Alama ya Alama (300-850)",
    "Score Band": "Kitengo cha Alama",
    "Percentile Rank": "Nafasi ya Asilimia",
    "Category Risk": "Hatari ya Kitengo",
    "Default Probability": "Uwezekano wa Kushindwa Kulipa",
    "Recommended Credit Limit": "Kikomo cha Mkopo Kinachopendekezwa",
}

PRIVACY_STATEMENT_SW = """
UFUATILIAJI WA FARAGHA NA ULINZI WA DATA

Ripoti hii imetolewa kutoka kwa data iliyofichwa na kukusanywa kwa kufuata:
- Sheria ya Ulinzi wa Data ya Kenya 2019
- k-Faragha (k≥10): Vipimo vyote vinakusanya data kutoka biashara angalau 10
- Faragha tofauti: Kelele iliyopimwa inatumika kwa vipimo nyeti vya kifedha
- Kupunguza Data: Sehemu zinazohitajika tu kwa madhumuni ya uchambuzi zimo
- Data ya biashara binafsi haijafunuliwa katika kiwango chochote cha ripoti hii

yanzisha: Jukwaa la Angavu Intelligence
Kitambulisho cha Ripoti: {report_id}
Iliyotolewa wakati: {generated_at}
"""

PRIVACY_STATEMENT = """
PRIVACY & DATA PROTECTION COMPLIANCE

This report is generated from anonymized, aggregated data in compliance with:
- Kenya Data Protection Act 2019
- k-Anonymity (k≥10): All metrics aggregate data from at least 10 unique businesses
- Differential Privacy: Calibrated noise applied to sensitive financial metrics
- Data Minimization: Only fields necessary for the analysis purpose are included
- No individual business data is exposed at any level of this report

Data sources: Transaction records from Msaidizi users who have consented to
anonymized data sharing for economic intelligence purposes.

Generated by: Angavu Intelligence Platform
Report ID: {report_id}
Generated at: {generated_at}
"""


class IntelligenceReportGenerator:
    """
    Generates formatted intelligence reports.

    Creates structured reports from intelligence product data
    with proper formatting, visualizations, and compliance statements.
    """

    def generate_html_report(
        self,
        product_code: str,
        data: Dict[str, Any],
        buyer_company: str = "",
        report_id: Optional[str] = None,
        language: str = "en",
    ) -> str:
        """
        Generate an HTML report for an intelligence product.

        Args:
            product_code: Product identifier (soko_pulse, etc.)
            data: Intelligence product response data
            buyer_company: Buyer's company name
            report_id: Unique report identifier
            language: Output language ('en' or 'sw')

        Returns:
            HTML string of the formatted report
        """
        template = REPORT_TEMPLATES.get(product_code)
        if not template:
            return f"<html><body><h1>Unknown product: {product_code}</h1></body></html>"

        if not report_id:
            report_id = f"RPT-{product_code.upper()}-{datetime.now(timezone.utc).strftime('%Y%m%d%H%M%S')}"

        sections_html = self._generate_sections(product_code, data, language=language)

        # Get translated title
        title_key = f"{product_code}_title"
        title = template['title']
        if language == 'sw':
            swahili_titles = {
                "soko_pulse": "Soko Pulse — Ripoti ya Utabiri wa Mahitaji ya FMCG",
                "biashara_pulse": "Angavu Pulse — Ripoti ya Fahirisi ya Shughuli za MSME",
                "alama_score": "Alama Score — Ripoti ya Tathmini ya Mkopo",
                "jamii_insights": "Jamii Insights — Ripoti ya Ujumuishaji wa Kifedha",
                "tax_base_estimation": "Makadirio ya Msingi wa Kodi — Ripoti ya Ujasusi wa Mapato",
                "distribution_gap": "Uchambuzi wa Mpango wa Usambazaji — Ripoti ya Ufunikaji wa Soko",
            }
            title = swahili_titles.get(product_code, title)

        privacy = PRIVACY_STATEMENT.format(
            report_id=report_id,
            generated_at=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
        )

        prepared_label = get_translation("prepared_for", language)
        focus_label = template['buyer_focus']

        html = f"""<!DOCTYPE html>
<html lang="{language}">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{template['title']}</title>
    <style>
        body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; margin: 40px; color: #333; line-height: 1.6; }}
        .header {{ background: linear-gradient(135deg, #1a5276, #2e86c1); color: white; padding: 30px; border-radius: 8px; margin-bottom: 30px; }}
        .header h1 {{ margin: 0; font-size: 24px; }}
        .header .subtitle {{ opacity: 0.9; margin-top: 8px; }}
        .section {{ margin-bottom: 30px; padding: 20px; background: #f8f9fa; border-radius: 8px; border-left: 4px solid #2e86c1; }}
        .section h2 {{ color: #1a5276; margin-top: 0; font-size: 18px; }}
        .metric {{ display: inline-block; margin: 10px 20px 10px 0; padding: 15px 20px; background: white; border-radius: 6px; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }}
        .metric .value {{ font-size: 28px; font-weight: bold; color: #1a5276; }}
        .metric .label {{ font-size: 12px; color: #666; text-transform: uppercase; }}
        .k-badge {{ display: inline-block; background: #27ae60; color: white; padding: 2px 8px; border-radius: 12px; font-size: 11px; }}
        table {{ width: 100%; border-collapse: collapse; margin: 15px 0; }}
        th, td {{ padding: 10px; text-align: left; border-bottom: 1px solid #ddd; }}
        th {{ background: #1a5276; color: white; }}
        tr:hover {{ background: #f0f0f0; }}
        .privacy {{ font-size: 11px; color: #888; border-top: 1px solid #ddd; padding-top: 20px; margin-top: 40px; white-space: pre-line; }}
        .trend-up {{ color: #27ae60; }}
        .trend-down {{ color: #e74c3c; }}
        .trend-stable {{ color: #f39c12; }}
    </style>
</head>
<body>
    <div class="header">
        <h1>{template['title']}</h1>
        <div class="subtitle">
            Prepared for: {buyer_company or 'Confidential'}<br>
            Focus: {template['buyer_focus']}<br>
            Period: {data.get('time_period', 'N/A')}
        </div>
    </div>

    {sections_html}

    <div class="privacy">{privacy}</div>
</body>
</html>"""

        return html

    def _generate_sections(self, product_code: str, data: Dict[str, Any], language: str = "en") -> str:
        """Generate HTML sections based on product type."""
        generators = {
            "soko_pulse": self._soko_pulse_sections,
            "biashara_pulse": self._biashara_pulse_sections,
            "alama_score": self._alama_score_sections,
            "jamii_insights": self._jamii_insights_sections,
            "tax_base_estimation": self._tax_base_sections,
            "distribution_gap": self._distribution_gap_sections,
        }
        generator = generators.get(product_code, self._generic_sections)
        return generator(data, language=language)

    def _soko_pulse_sections(self, d: Dict, language: str = "en") -> str:
        g = get_translation
        price = d.get("price_intelligence", {})
        forecast = d.get("forecast", {})
        return f"""
    <div class="section">
        <h2>📊 {g('demand_overview', language)}</h2>
        <div class="metric"><div class="value">{d.get('total_volume', 0):,.0f}</div><div class="label">{g('total_volume', language)}</div></div>
        <div class="metric"><div class="value">{d.get('avg_daily_volume', 0):,.0f}</div><div class="label">{g('avg_daily_volume', language)}</div></div>
        <div class="metric"><div class="value">{d.get('vendor_count', 0)}</div><div class="label">{g('vendors', language)} <span class="k-badge">k={d.get('vendor_count', 0)}</span></div></div>
        <div class="metric"><div class="value trend-{d.get('demand_trend', 'stable')}">{g(d.get('demand_trend', 'stable'), language)}</div><div class="label">{g('demand_trend', language)}</div></div>
    </div>
    <div class="section">
        <h2>💰 {g('price_intelligence', language)}</h2>
        <div class="metric"><div class="value">KES {price.get('avg_price', 0):,.0f}</div><div class="label">{g('average_price', language)}</div></div>
        <div class="metric"><div class="value">KES {price.get('min_price', 0):,.0f} - {price.get('max_price', 0):,.0f}</div><div class="label">{g('price_range', language)}</div></div>
        <div class="metric"><div class="value trend-{price.get('price_trend', 'stable')}">{g(price.get('price_trend', 'stable'), language)}</div><div class="label">{g('demand_trend', language)}</div></div>
    </div>
    {"" if not forecast else f'''
    <div class="section">
        <h2>🔮 {g('demand_forecast', language)}</h2>
        <div class="metric"><div class="value">{forecast.get("forecasted_volume", 0):,.0f}</div><div class="label">{g('demand_forecast', language)}</div></div>
    </div>
    '''}
    """

    def _biashara_pulse_sections(self, d: Dict, language: str = "en") -> str:
        formation = d.get("business_formation", {})
        return f"""
    <div class="section">
        <h2>📈 Activity Indices</h2>
        <div class="metric"><div class="value">{d.get('activity_index', 0)}</div><div class="label">Activity Index (0-100)</div></div>
        <div class="metric"><div class="value">{d.get('growth_index', 0)}</div><div class="label">Growth Index (0-100)</div></div>
        <div class="metric"><div class="value">{d.get('estimated_businesses', 0):,}</div><div class="label">Estimated Businesses <span class="k-badge">k={d.get('users_included', 0)}</span></div></div>
        <div class="metric"><div class="value">{d.get('mpesa_penetration_pct', 0)}%</div><div class="label">M-Pesa Penetration</div></div>
    </div>
    <div class="section">
        <h2>🏢 Business Formation</h2>
        <div class="metric"><div class="value">{formation.get('new_businesses_est', 0)}</div><div class="label">New Businesses (Est.)</div></div>
        <div class="metric"><div class="value">{formation.get('net_change', 0)}</div><div class="label">Net Change</div></div>
        <div class="metric"><div class="value">{formation.get('formation_rate', 0)}</div><div class="label">Formation Rate (per 1000)</div></div>
    </div>
    <div class="section">
        <h2>🏭 Sector Breakdown</h2>
        <table><tr><th>Sector</th><th>Activity Share</th><th>Revenue Share</th><th>Businesses</th><th>Trend</th></tr>
        {"".join(f'<tr><td>{s["sector"]}</td><td>{s["activity_share_pct"]}%</td><td>{s["revenue_share_pct"]}%</td><td>{s["business_count"]}</td><td>{s["trend"]}</td></tr>' for s in d.get('sector_breakdown', [])[:10])}
        </table>
    </div>"""

    def _alama_score_sections(self, d: Dict, language: str = "en") -> str:
        g = get_translation
        components = d.get("components", {})
        risk = d.get("risk_indicators", {})
        return f"""
    <div class="section">
        <h2>🎯 {g('score_overview', language)}</h2>
        <div class="metric"><div class="value" style="font-size:48px">{d.get('alama_score', 0)}</div><div class="label">{g('alama_score', language)} (300-850)</div></div>
        <div class="metric"><div class="value">{g(d.get('score_band', 'fair'), language)}</div><div class="label">{g('score_band', language)}</div></div>
        <div class="metric"><div class="value">{d.get('percentile', 0)}%</div><div class="label">{g('percentile', language)}</div></div>
    </div>
    <div class="section">
        <h2>⚠️ {g('risk_assessment', language)}</h2>
        <div class="metric"><div class="value">{risk.get('default_probability', 0):.2%}</div><div class="label">{g('default_probability', language)}</div></div>
        <div class="metric"><div class="value">KES {risk.get('recommended_credit_limit_kes', 0):,.0f}</div><div class="label">{g('credit_limit', language)}</div></div>
        <div class="metric"><div class="value">{risk.get('category_risk', 'N/A')}</div><div class="label">{g('risk_assessment', language)}</div></div>
    </div>"""

    def _jamii_insights_sections(self, d: Dict, language: str = "en") -> str:
        metrics = d.get("inclusion_metrics", {})
        impact = d.get("program_impact")
        barriers = d.get("barriers", [])
        return f"""
    <div class="section">
        <h2>🌍 Financial Inclusion Index</h2>
        <div class="metric"><div class="value">{metrics.get('financial_inclusion_index', 0)}</div><div class="label">Inclusion Index (0-100)</div></div>
        <div class="metric"><div class="value">{metrics.get('digital_payment_adoption', 0)}%</div><div class="label">Digital Payment Adoption</div></div>
        <div class="metric"><div class="value">{metrics.get('savings_behavior_score', 0)}</div><div class="label">Savings Score</div></div>
        <div class="metric"><div class="value">{metrics.get('credit_access_score', 0)}</div><div class="label">Credit Access Score</div></div>
        <div class="metric"><div class="value">{d.get('sample_size', 0)}</div><div class="label">Sample Size <span class="k-badge">k={d.get('sample_size', 0)}</span></div></div>
    </div>
    <div class="section">
        <h2>👥 Demographics</h2>
        <div class="metric"><div class="value">{d.get('youth_owned_pct', 0)}%</div><div class="label">Youth-Owned</div></div>
        <div class="metric"><div class="value">{d.get('women_owned_pct', 0)}%</div><div class="label">Women-Owned</div></div>
        <div class="metric"><div class="value">KES {d.get('avg_monthly_income_kes', 0):,.0f}</div><div class="label">Avg Monthly Income</div></div>
        <div class="metric"><div class="value">{d.get('employment_created', 0):,}</div><div class="label">Employment Created</div></div>
    </div>
    {"" if not impact else f'''
    <div class="section">
        <h2>📊 Program Impact</h2>
        <div class="metric"><div class="value">{impact.get("program_name", "N/A")}</div><div class="label">Program</div></div>
        <div class="metric"><div class="value">{impact.get("beneficiary_count", 0):,}</div><div class="label">Beneficiaries</div></div>
        <div class="metric"><div class="value">{impact.get("pre_program_index", 0):.1f} → {impact.get("post_program_index", 0):.1f}</div><div class="label">Index Change</div></div>
        <div class="metric"><div class="value">+{impact.get("impact_delta", 0):.1f}</div><div class="label">Impact Delta</div></div>
    </div>
    '''}
    <div class="section">
        <h2>🚧 Barriers to Inclusion</h2>
        <table><tr><th>Barrier</th><th>Severity</th><th>Affected %</th><th>Recommended Intervention</th></tr>
        {"".join(f'<tr><td>{b["barrier"]}</td><td>{b["severity"]}</td><td>{b["affected_pct"]}%</td><td>{b.get("recommended_intervention", "N/A")}</td></tr>' for b in barriers)}
        </table>
    </div>"""

    def _tax_base_sections(self, d: Dict, language: str = "en") -> str:
        tax = d.get("tax_estimates", {})
        return f"""
    <div class="section">
        <h2>💰 Tax Base Overview</h2>
        <div class="metric"><div class="value">{d.get('estimated_businesses', 0):,}</div><div class="label">Estimated Businesses <span class="k-badge">k={d.get('users_included', 0)}</span></div></div>
        <div class="metric"><div class="value">{d.get('formalized_businesses', 0):,}</div><div class="label">Formalized</div></div>
        <div class="metric"><div class="value">{d.get('formalization_gap_pct', 0)}%</div><div class="label">Formalization Gap</div></div>
    </div>
    <div class="section">
        <h2>📊 Tax Estimates</h2>
        <div class="metric"><div class="value">KES {tax.get('estimated_total_revenue_kes', 0):,.0f}</div><div class="label">Total Revenue (Annualized)</div></div>
        <div class="metric"><div class="value">KES {tax.get('estimated_vat_collectible_kes', 0):,.0f}</div><div class="label">VAT Collectible</div></div>
        <div class="metric"><div class="value">KES {tax.get('tax_gap_kes', 0):,.0f}</div><div class="label">Tax Gap</div></div>
        <div class="metric"><div class="value">{tax.get('tax_compliance_rate', 0)}%</div><div class="label">Compliance Rate</div></div>
    </div>
    <div class="section">
        <h2>🏭 Sector Breakdown</h2>
        <table><tr><th>Sector</th><th>Revenue (KES)</th><th>VAT Base</th><th>VAT Collectible</th><th>Businesses</th><th>Compliance</th></tr>
        {"".join(f'<tr><td>{s["sector"]}</td><td>{s["estimated_revenue_kes"]:,.0f}</td><td>{s["vat_base_kes"]:,.0f}</td><td>{s["vat_collectible_kes"]:,.0f}</td><td>{s["business_count"]}</td><td>{s["compliance_rate"]}%</td></tr>' for s in d.get('sector_breakdown', [])[:10])}
        </table>
    </div>"""

    def _distribution_gap_sections(self, d: Dict, language: str = "en") -> str:
        coverage = d.get("coverage", {})
        return f"""
    <div class="section">
        <h2>📍 Coverage Overview</h2>
        <div class="metric"><div class="value">{coverage.get('total_markets_surveyed', 0)}</div><div class="label">Markets Surveyed</div></div>
        <div class="metric"><div class="value">{coverage.get('markets_with_product', 0)}</div><div class="label">Markets Covered</div></div>
        <div class="metric"><div class="value">{coverage.get('markets_without_product', 0)}</div><div class="label">Gap Markets</div></div>
        <div class="metric"><div class="value">{coverage.get('coverage_pct', 0)}%</div><div class="label">Coverage</div></div>
        <div class="metric"><div class="value">{coverage.get('penetration_rate', 0)}%</div><div class="label">Penetration Rate</div></div>
    </div>
    <div class="section">
        <h2>🎯 Opportunity Sizing</h2>
        <div class="metric"><div class="value">KES {d.get('gap_revenue_potential_kes', 0):,.0f}</div><div class="label">Gap Revenue Potential</div></div>
        <div class="metric"><div class="value">{d.get('gap_market_population', 0):,}</div><div class="label">Gap Market Population</div></div>
        <div class="metric"><div class="value">{d.get('estimated_roi_pct', 0)}%</div><div class="label">Estimated ROI</div></div>
        <div class="metric"><div class="value">KES {d.get('investment_required_kes', 0):,.0f}</div><div class="label">Investment Required</div></div>
    </div>
    <div class="section">
        <h2>🗺️ Priority Gap Markets</h2>
        <table><tr><th>Market</th><th>Demand Index</th><th>Revenue Potential</th><th>Priority</th><th>Action</th></tr>
        {"".join(f'<tr><td>{g["market_id"]}</td><td>{g["demand_index"]}</td><td>KES {g["revenue_potential_kes"]:,.0f}</td><td>{g["priority_rank"]}</td><td>{g.get("recommended_action", "N/A")}</td></tr>' for g in d.get('gap_markets', [])[:10])}
        </table>
    </div>"""

    def _generic_sections(self, d: Dict, language: str = "en") -> str:
        """Fallback generic sections."""
        metrics_html = ""
        for key, value in d.items():
            if isinstance(value, (int, float, str)) and key not in ("product", "version"):
                metrics_html += f'<div class="metric"><div class="value">{value}</div><div class="label">{key.replace("_", " ").title()}</div></div>'
        return f'<div class="section"><h2>📊 Key Metrics</h2>{metrics_html}</div>'

    def generate_summary_text(
        self,
        product_code: str,
        data: Dict[str, Any],
    ) -> str:
        """
        Generate a plain-text summary for WhatsApp/Telegram delivery.

        Args:
            product_code: Product identifier
            data: Intelligence product response data

        Returns:
            Plain text summary
        """
        generators = {
            "soko_pulse": self._soko_text_summary,
            "biashara_pulse": self._biashara_text_summary,
            "alama_score": self._alama_text_summary,
            "jamii_insights": self._jamii_text_summary,
            "tax_base_estimation": self._tax_text_summary,
            "distribution_gap": self._dist_gap_text_summary,
        }
        generator = generators.get(product_code, lambda d: "Report generated successfully.")
        return generator(data)

    def _soko_text_summary(self, d: Dict) -> str:
        price = d.get("price_intelligence", {})
        return (
            f"📊 *Soko Pulse — Demand Report*\n"
            f"Region: {d.get('region', 'N/A')} | Category: {d.get('product_category', 'N/A')}\n\n"
            f"📈 Total Volume: {d.get('total_volume', 0):,.0f}\n"
            f"📊 Daily Avg: {d.get('avg_daily_volume', 0):,.0f}\n"
            f"💹 Trend: {d.get('demand_trend', 'N/A').title()}\n"
            f"💰 Avg Price: KES {price.get('avg_price', 0):,.0f}\n"
            f"🏪 Vendors: {d.get('vendor_count', 0)}\n"
            f"🔒 k-Anonymity: {d.get('vendor_count', 0)} (threshold: 10)"
        )

    def _biashara_text_summary(self, d: Dict) -> str:
        return (
            f"📊 *Angavu Pulse — MSME Activity*\n"
            f"Region: {d.get('region', 'N/A')}\n\n"
            f"📈 Activity Index: {d.get('activity_index', 0)}/100\n"
            f"💹 Growth Index: {d.get('growth_index', 0)}/100\n"
            f"🏢 Businesses: {d.get('estimated_businesses', 0):,}\n"
            f"📱 M-Pesa: {d.get('mpesa_penetration_pct', 0)}%\n"
            f"🏭 Top Sectors: {', '.join(d.get('top_sectors', [])[:3])}"
        )

    def _alama_text_summary(self, d: Dict) -> str:
        return (
            f"🎯 *Alama Score — Credit Assessment*\n"
            f"Business: {d.get('business_hash', 'N/A')[:8]}...\n\n"
            f"📊 Score: {d.get('alama_score', 0)}/850 ({d.get('score_band', 'N/A').title()})\n"
            f"📈 Percentile: {d.get('percentile', 0)}%\n"
            f"💰 Daily Revenue: KES {d.get('avg_daily_revenue_kes', 0):,.0f}\n"
            f"📊 Growth: {d.get('growth_trajectory', 'N/A').title()}\n"
            f"⚠️ Risk: {d.get('risk_indicators', {}).get('category_risk', 'N/A').title()}"
        )

    def _jamii_text_summary(self, d: Dict) -> str:
        m = d.get("inclusion_metrics", {})
        return (
            f"🌍 *Jamii Insights — Financial Inclusion*\n"
            f"Region: {d.get('region', 'N/A')}\n\n"
            f"📊 Inclusion Index: {m.get('financial_inclusion_index', 0)}/100\n"
            f"📱 Digital Payments: {m.get('digital_payment_adoption', 0)}%\n"
            f"💰 Savings Score: {m.get('savings_behavior_score', 0)}\n"
            f"👥 Women-Owned: {d.get('women_owned_pct', 0)}%\n"
            f"👷 Employment: {d.get('employment_created', 0):,}"
        )

    def _tax_text_summary(self, d: Dict) -> str:
        tax = d.get("tax_estimates", {})
        return (
            f"💰 *Tax Base Estimation*\n"
            f"Region: {d.get('region', 'N/A')}\n\n"
            f"🏢 Businesses: {d.get('estimated_businesses', 0):,}\n"
            f"📋 Formalized: {d.get('formalized_businesses', 0):,}\n"
            f"💰 Revenue: KES {tax.get('estimated_total_revenue_kes', 0):,.0f}\n"
            f"💰 VAT Collectible: KES {tax.get('estimated_vat_collectible_kes', 0):,.0f}\n"
            f"📊 Compliance: {tax.get('tax_compliance_rate', 0)}%"
        )

    def _dist_gap_text_summary(self, d: Dict) -> str:
        c = d.get("coverage", {})
        return (
            f"📍 *Distribution Gap Analysis*\n"
            f"Category: {d.get('product_category', 'N/A')}\n\n"
            f"📊 Coverage: {c.get('coverage_pct', 0)}%\n"
            f"🏪 Covered: {c.get('markets_with_product', 0)}/{c.get('total_markets_surveyed', 0)}\n"
            f"📍 Gap Markets: {c.get('markets_without_product', 0)}\n"
            f"💰 Potential: KES {d.get('gap_revenue_potential_kes', 0):,.0f}\n"
            f"📈 ROI: {d.get('estimated_roi_pct', 0)}%"
        )

    # ── Swahili Text Summaries ──────────────────────────────────────

    def generate_summary_text_sw(
        self,
        product_code: str,
        data: Dict[str, Any],
    ) -> str:
        """
        Generate a plain-text summary in Swahili for WhatsApp/Telegram delivery.

        Args:
            product_code: Product identifier
            data: Intelligence product response data

        Returns:
            Swahili plain text summary
        """
        generators = {
            "soko_pulse": self._soko_text_summary_sw,
            "biashara_pulse": self._biashara_text_summary_sw,
            "alama_score": self._alama_text_summary_sw,
            "jamii_insights": self._jamii_text_summary_sw,
        }
        generator = generators.get(product_code, lambda d: "Ripoti imetolewa kwa mafanikio.")
        return generator(data)

    def _soko_text_summary_sw(self, d: Dict) -> str:
        price = d.get("price_intelligence", {})
        return (
            f"📊 *Soko Pulse — Ripoti ya Mahitaji*\n"
            f"Eneo: {d.get('region', 'N/A')} | Kitengo: {d.get('product_category', 'N/A')}\n\n"
            f"📈 Jumla ya Kiasi: {d.get('total_volume', 0):,.0f}\n"
            f"📊 Wastani wa Siku: {d.get('avg_daily_volume', 0):,.0f}\n"
            f"💹 Mwelekeo: {d.get('demand_trend', 'N/A').title()}\n"
            f"💰 Wastani wa Bei: KES {price.get('avg_price', 0):,.0f}\n"
            f"🏪 Wachuuzi: {d.get('vendor_count', 0)}\n"
            f"🔒 k-Faragha: {d.get('vendor_count', 0)} (kikomo: 10)"
        )

    def _biashara_text_summary_sw(self, d: Dict) -> str:
        return (
            f"📊 *Angavu Pulse — Shughuli za Biashara Ndogo*\n"
            f"Eneo: {d.get('region', 'N/A')}\n\n"
            f"📈 Kiashirio cha Shughuli: {d.get('activity_index', 0)}/100\n"
            f"💹 Kiashirio cha Ukuaji: {d.get('growth_index', 0)}/100\n"
            f"🏢 Biashara: {d.get('estimated_businesses', 0):,}\n"
            f"📱 M-Pesa: {d.get('mpesa_penetration_pct', 0)}%\n"
            f"🏭 Sekta Kuu: {', '.join(d.get('top_sectors', [])[:3])}"
        )

    def _alama_text_summary_sw(self, d: Dict) -> str:
        return (
            f"🎯 *Alama Score — Tathmini ya Mkopo*\n"
            f"Biashara: {d.get('business_hash', 'N/A')[:8]}...\n\n"
            f"📊 Alama: {d.get('alama_score', 0)}/850 ({d.get('score_band', 'N/A').title()})\n"
            f"📈 Asilimia: {d.get('percentile', 0)}%\n"
            f"💰 Mapato ya Siku: KES {d.get('avg_daily_revenue_kes', 0):,.0f}\n"
            f"📊 Ukuaji: {d.get('growth_trajectory', 'N/A').title()}\n"
            f"⚠️ Hatari: {d.get('risk_indicators', {}).get('category_risk', 'N/A').title()}"
        )

    def _jamii_text_summary_sw(self, d: Dict) -> str:
        m = d.get("inclusion_metrics", {})
        return (
            f"🌍 *Jamii Insights — Ujumuishaji wa Kifedha*\n"
            f"Eneo: {d.get('region', 'N/A')}\n\n"
            f"📊 Kiashirio cha Ujumuishaji: {m.get('financial_inclusion_index', 0)}/100\n"
            f"📱 Malipo ya Dijitali: {m.get('digital_payment_adoption', 0)}%\n"
            f"💰 Alama ya Akiba: {m.get('savings_behavior_score', 0)}\n"
            f"👥 Wanawake Wanaomiliki: {d.get('women_owned_pct', 0)}%\n"
            f"👷 Ajira: {d.get('employment_created', 0):,}"
        )
